### ISSUE TITLE
Semantic versioning and missing functionality

### ISSUE THREAD

**Issue by rogerhmar** [PragmaticFlow/NBomber#147]
Version 0.11.0 is breaking, and should be a major update.

And also: You have removed the pause-step:
* The documentation is not updated
* What is the proposed pattern for controlling the load from the loadtests?

**Comment by AntyaDev** [comment]
Hi @rogerhmar 

regarding pause [step](https://github.com/PragmaticFlow/NBomber/issues/148#issuecomment-492659386)

**Comment by AntyaDev** [comment]
@rogerhmar 
yes, you are right, it's breaking.
on the other hand, we are not ready for version 1 which is basically saying that API is completed and stabilized. 

What is you suggestions?

**Comment by AntyaDev** [comment]
@rogerhmar can I close it?

**Comment by rogerhmar** [comment]
> @rogerhmar
> yes, you are right, it's breaking.
> on the other hand, we are not ready for version 1 which is basically saying that API is completed and stabilized.
> 
> What is you suggestions?

Good question. 
Looking at  https://semver.org/#how-do-i-know-when-to-release-100 it says 

> If your software is being used in production, it should probably already be 1.0.0.

But what does "in production" mean for at test framework? I am not sure.

But for me it seems like the last release removed the posibility to control the load on the system under test. That it a major change on the API. If I add task.Delay in my steps, I will clearly mess up my results. It I add "pause" steps, these would need to have separate names, and they will all be included in the report as separate steps.

Any suggestions on how to controll the load? Are you planning to have some sort of scheduling mechanism?

**Comment by AntyaDev** [comment]
Hi, @rogerhmar sorry for the big delay.
"NBomber, is almost production ready", but still we add new features every release which breaks API, therefore, it's not under v1 but under v0.

> But what does "in production" mean for at test framework? I am not sure.
Look, we still working on a fundamental feature which should simplify a way how you define scenarios and steps. For example, we added **repeatCount** which will affect how many times your step will be repeated for every turn. We made optionally argument ConnectionPool.  

> Any suggestions on how to control the load? Are you planning to have some sort of scheduling mechanism?

Can you explain your test scenario?

**Comment by AntyaDev** [comment]
Hi @rogerhmar , any news?
