### ISSUE TITLE
Add ability to add ramp users per second

### ISSUE THREAD

**Issue by AntyaDev** [PragmaticFlow/NBomber#15]
rampUsers(500) over (10 minutes)).throttle(reachRps(100) in (10 seconds), holdFor(10 minutes)

**Comment by tkallsen** [comment]
Hi, was anything developed for this? Would be great to for ramping up complex scenarios so that for instance 200 login-steps doesn't get executed at the same time.

**Comment by AntyaDev** [comment]
Hi @tkallsen 
This feature in the top priority and even API was prototiped but unfortunately I don't have much time for this at the moment. I hope that in week or two I will continue progressing
