### ISSUE TITLE
ScenarioBuilder.WithDuration(x) not respected

### ISSUE THREAD

**Issue by ykns** [PragmaticFlow/NBomber#151]
Hi there,

When executing tests I've noticed that tests are going way over the time specified by ScenarioBuilder.WithDuration. For instance, I specified 120s as the duration but the test took 26 minutes. Any ideas why that maybe? Do I have observe the cancellation token in the StepContext?

Kind regards,
Yakeen

**Comment by AntyaDev** [comment]
Hi @ykns, yes you have context.CancellationToken which you can pass in your environment (for example: mongoClient, httpClient)
you can take a look at this example: https://github.com/PragmaticFlow/NBomber/blob/dev/examples/CSharp/CSharp.Examples/Scenarios/Http.cs#L22

**Comment by ykns** [comment]
Indeed I had realised my mistake and have corrected it.  Thanks for getting back to me!
