### ISSUE TITLE
Add the ability to return a Response that retries the Step with an optional interval

### ISSUE THREAD

**Issue by Chralex** [PragmaticFlow/NBomber#156]
I have cases where background jobs on the target application needs to run before we get the desired response to continue to the next step and we want to keep re-running a step until the appropriate data has been returned, usually since the rest of the steps are dependent on this. 

The background jobs are run in regular intervals such as 10 seconds or two minutes.

In the statistics you would keep adding the time the operation took until the step is finished.
E.g. first time the step runs it gets a response the response took 100ms, I return a `Response.Retry(TimeSpan.FromSeconds(10))`, the flow runner waits 10 seconds next time it gets a different response say it took 82ms and it is the response that we want to finish the step so an `Response.Ok()` is returned and the total time shown in the statistics would be 182ms.

**Comment by AntyaDev** [comment]
Hi @Chralex. I think you can use TestInt and check some response until you get a proper one
