### ISSUE TITLE
NBomber won't run from NUnit

### ISSUE THREAD

**Issue by al007** [PragmaticFlow/NBomber#160]
https://github.com/PragmaticFlow/NBomber/blob/4c6ccbc7845fda6799b7acc94784e382e340b908/src/NBomber/Infra/Dependency.fs#L93

The GetEntryAssembly method can return null when a managed assembly has been loaded from an unmanaged application.
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getentryassembly?view=netframework-4.8

**Comment by AntyaDev** [comment]
Hi @al007
What version of NBomber did you use?

**Comment by al007** [comment]
Latest stable from NuGet -- 0.13.0

**Comment by AntyaDev** [comment]
thanks @al007 , will take a look soon

**Comment by AntyaDev** [comment]
Hi @al007 ,
Sorry I was very busy and didn't have time to check it.
I will do my best on this week.

**Comment by AntyaDev** [comment]
Hi @al007 
How I can simulate the error?
I tried this example and it works
https://github.com/PragmaticFlow/NBomber/blob/dev/examples/CSharp/CSharp.Examples.NUnit/Tests.cs#L25

**Comment by AntyaDev** [comment]
ping @al007
