### ISSUE TITLE
Be able to cancel the whole scenario from within the step

### ISSUE THREAD

**Issue by CezaryKMakingWaves** [PragmaticFlow/NBomber#161]
Hi,

Thanks for the effort you put so for in this very helpful framework. I am now facing an issue of being able to terminate the whole scenario from withing the step execution.

Motivation for that is some of the steps are prerequisites to execute others, e.g. authentication session. So it doesn't make any sense to progress in such a situation.

Maybe some exposure of the hidden CancellationTokenSource.

EDIT: By cancelling I mean stop looping through the scenario again

Best regards

**Comment by AntyaDev** [comment]
Hi @CezaryKMakingWaves 
Thanks for such cool feedback!!! 
Actually, I thought about adding validation on WarmUp step and in case if many tasks failed then we just stop the execution. It's on my priority list and I hope in the next minor version I will add it.
Does it make sense?

**Comment by AntyaDev** [comment]
Hi @CezaryKMakingWaves 
I have added a validation on warm-up which will stop execution if warm-up fails.

For your specific case, I suggest implementing Scenario.WithInit() and run all necessary prerequisites to fulfill your requirements.
