### ISSUE TITLE
Be able to specify number of scenario executions

### ISSUE THREAD

**Issue by ghost** [PragmaticFlow/NBomber#162]
Hi,

This is a suggestion to have a possibility to specify a number of scenario executions rather than the duration of "bombing".

Motivation: be able to accomplish a fixed scenario iterations, whereas total execution time can't be predicted

Best regards

**Comment by AntyaDev** [comment]
Hi @CezaryKMakingWaves 

Yep, I want to add this for sure, especially for this I did some changes in the latest v0.14.0 version of NBomber. 
I hope in the next minor release I will be able to add it.

**Comment by bper19** [comment]
This would be very useful to me, too. Any updates on implementation?

**Comment by AntyaDev** [comment]
Hi @bper19 ,

Actually now I am finishing a very important feature of providing dynamic workload

type LoadSimulation =
    | Constant  of copiesCount:int * duration:TimeSpan
    | AddPerSec of copiesCount:int * duration:TimeSpan
    | RampTo    of copiesCount:int * duration:TimeSpan

**Comment by AntyaDev** [comment]
Hi @bper19, @ghost
I have added https://github.com/PragmaticFlow/NBomber/commit/5b90089c0154ef10b4f5db84956eb63c815971f5
