### ISSUE TITLE
Newbie Question - Load testing (stress tests) not ramping up

### ISSUE THREAD

**Issue by andrewharry** [PragmaticFlow/NBomber#163]
I am trying to load test an API using NBomber.  The problem is that it doesn't seem to really increase the load when I change the config to use more threads and greater concurrency.
4 thread running 20 concurrent is putting the same load as 10 threads with 50 concurrent.

Because of the complexity in the API calls I couldn't just use your NBomber.Http library (Although I am hoping the new features you have released in 0.14 for passing data via the context might help)

Instead I am wrapping the API calls inside Step.Create.  This works and it does put load on the system.  But it doesn't really seem to push the API particularly hard.  

I have access to another load test tool which isn't particularly nice to use - But it does put plenty of load on the system (65% CPU on the server with timeouts etc)

Both of these tools I am running on my local PC on the same network as the target API server.

Any hints or ideas what could be wrong?

**Comment by AntyaDev** [comment]
Hi @andrewharry ,

First, try the latest version 0.14.0 it might give a bit better results.
If "another tool" is giving you API to specify how many requests it should send then probably it doesn't wait on responses from previous steps. I mean that the test runner is working a bit differently without any backpressure. This feature is on my list of top priority and I hope in the next release I will add this functionality.

I think you can try cluster: 
https://github.com/PragmaticFlow/NBomber/tree/dev/examples/CSharp/CSharp.Examples.Cluster  

Can you please give me a link on the tool which you are using?

**Comment by andrewharry** [comment]
The other tool was written by a contractor in java to get some rough numbers.  It is downloading the API content etc.  It also is leaving hundreds of open TCP connections which is causing it's own issues.

I wanted a second opinion / tool to try and see if comparable numbers are produced by both.

I will try the new version (0.14) tomorrow and report back here. 

Thanks again for your outstanding support

**Comment by AntyaDev** [comment]
Sure.
I have compared NBomber with other tools it shows very similar results.
As I understand, you are testing only one endpoint using one NBomber.Step, correct?

**Comment by andrewharry** [comment]
I didn't realise the ThreadCount had been disabled.
Turns out I was hitting the maxconnection default of only 2 concurrent connections

```
  <system.net>
    <connectionManagement>
      <clear/>
      <add address="*" maxconnection="10"/>
    </connectionManagement>
  </system.net>
```

**Comment by AntyaDev** [comment]
Hi @andrewharry 
Regarding the latest changes, you can read release notes: 
https://github.com/PragmaticFlow/NBomber/releases/tag/v0.14.0

I am time to time introducing breaking changes since we are on 0.* version.

Regarding your latest comment about concurrent connections - it's why better to use .NET Core, it has better performance of HTTP client and it doesn't have a limitation on connections which you mentioned. So you basically don't need any custom configuration, just use latest .NET Core.
