### ISSUE TITLE
Accessing stats before the end of the test

### ISSUE THREAD

**Issue by CamilBouzidi** [PragmaticFlow/NBomber#164]
Hello,

I enjoy using the framework a lot, but it seems that I cannot access the stats before the end of the test. If my test lasts more than a minute, I would like to be able to access real-time stats every 10 seconds or so.

Is this a feature that is available? If not, will it be added at some point?

Thank you for the great framework, and keep up the good work!

**Comment by AntyaDev** [comment]
Hi @CamilBouzidi 
Thank you for such amazing feedback!!!

Yep, I am working on it now and hopefully will finish on this weekend.

Btw, are using it in cluster mode or just single node?

**Comment by CamilBouzidi** [comment]
Hello,

Thank you for the quick response, I'll be looking forward to this feature :)

I am using it as a single node, currently!

**Comment by AntyaDev** [comment]
Hi @CamilBouzidi 
I have added real-time metrics. 
you can try it via installing latest beta (0.15.0-beta)

**Comment by CamilBouzidi** [comment]
Hello @AntyaDev,
This is some amazing work! Thank yo so much for adding this feature :)
