### ISSUE TITLE
Websockets, the way back

### ISSUE THREAD

**Issue by riccardobecker** [PragmaticFlow/NBomber#167]
first of all, what a nice framework for creating load tests, really cool.

I am planning on using it on our websocket server implementation. Connecting and sending messages to the server works perfectly fine based on the simple example.

I also want to check if the response back (server sends something to the client that is) is received and correct. What would be the best way to do this and keep it scalable and running?

I prefer planning loadtests in thousands of clients.

regards and thanks in advance,
Riccardo

**Comment by AntyaDev** [comment]
Hi @riccardobecker 
Thank you for your great feedback!

First, are you using NBomber as a cluster? 

Regarding the correctness of response, can you please give more description?

**Comment by riccardobecker** [comment]
Hi Antya, not using it as a cluster (yet) but first wanted to setup a simple two-way fullduplex set. So client sends a request message of a certain type, server responds to that message by sending e.g. an acknowledgement of correct receiving the request.

When that is working as expected run it on Azure appservice (PaaS before IaaS, no VM's) and then start scaling out and up for hammering the websocket server.

You think NBomber will suit this scenario?
regards

**Comment by AntyaDev** [comment]
> You think NBomber will suit this scenario?
Yep.
I am using NBomber to cover very complex flow (this is a key feature of NBomber). For example, we push data to Kafka, then the data consumed by some workers, afterward, the worker will push to Kafka back and eventually, data should be available in NoSQL storage plush push notification should be received via WebSocket. 

All those multi-steps could be tracked via NBomber and I can see where is a bigger latency etc.

**Comment by AntyaDev** [comment]
Hi @riccardobecker 
I removed the cluster to rework it.

**Comment by riccardobecker** [comment]
Ok thought so. Good luck with it!

**Comment by AntyaDev** [comment]
thanks, it's already in test
