### ISSUE TITLE
Real-time stats do not work in 0.15.0-beta3

### ISSUE THREAD

**Issue by CamilBouzidi** [PragmaticFlow/NBomber#168]
Hello @AntyaDev!

The step pausing and hiding features are awesome! It's super useful to have a much shorter report. I think, though, that the recent features have affected the real time stats, as going from 0.15.0-beta to beta3 prevents me from seeing the live stats in my InfluxDb sink.

Do you know what might cause this? Am I missing a (new) parameter that I must pass to the step builder or scenario builder?

As always, thank you for your amazing work!

**Comment by AntyaDev** [comment]
Hello @CamilBouzidi 

Thanks for such amazing feedback.
Yes, you are right I have changed a bit how we store metrics.

You now should filter by tags:
scenario
step
operation:  "warmup" | "bombing" | "complete"

you can check all details here:
https://github.com/PragmaticFlow/NBomber.Sinks.InfluxDB/blob/master/src/NBomber.Sinks.InfluxDB/InfluxDBSink.fs#L15

FYI: usually after release, I will publish all these changes in doc and in the release notes like this for example: https://github.com/PragmaticFlow/NBomber/releases/tag/v0.14.0

**Comment by CamilBouzidi** [comment]
Hi @AntyaDev,

I see, thank you for the clarification! Any timeline for the next release? I'm really excited to get my hands on it!

**Comment by AntyaDev** [comment]
Hi @CamilBouzidi ,

I need to check how realtime works for the cluster mode and then will publish a release version.
Can it wait till Saturday? (on Saturday I will have free time to complete)

**Comment by CamilBouzidi** [comment]
Hello @AntyaDev,

Absolutely! It is your project, after all.

Thank you for your hard work!

**Comment by AntyaDev** [comment]
Hi @Caballero77 
shipped v0.15.0 https://github.com/PragmaticFlow/NBomber/releases/tag/v0.15.0
