### ISSUE TITLE
Question: Planning non-linear load

### ISSUE THREAD

**Issue by gunmaden** [PragmaticFlow/NBomber#169]
Great framework. Planning to use it in dev. This cause a question: Is there in your plans adding feature such as non-linear load testing (min / max concurrent running scenarios) with ability to configure increasing parallel executions per second/minute?

**Comment by AntyaDev** [comment]
Hi @gunmaden 
Thanks for cool feedback!
Yep, this is in TOP priority for me now.
I think in next version I will release this feature.
Also you can take a look on cluster it will give you more real load.
Are you testing an API?

**Comment by gunmaden** [comment]
> Are you testing an API?

**Comment by gunmaden** [comment]
Also would be great if I could configure and pass Logger for executor

**Comment by AntyaDev** [comment]
Hey @gunmaden 
I think you can pass the logger but not sure if it can capture all the necessary things.
https://github.com/PragmaticFlow/NBomber/blob/dev/examples/CSharp/CSharp.Examples/config.json#L17

Regarding the timelines: I will be very busy the whole of November, therefore I think that the most realistic will be in the middle of December.

**Comment by gunmaden** [comment]
@AntyaDev Hi, any news about non-linear load?

**Comment by AntyaDev** [comment]
Hi @gunmaden 
Almost there, I am working in this branch https://github.com/PragmaticFlow/NBomber/tree/load-spec

you can find a basic example in https://github.com/PragmaticFlow/NBomber/blob/load-spec/examples/FSharp/FSharp.Examples/Scenarios/Http.fs

```fsharp
    let scenario = Scenario.create "test_nbomber" [step]
                   |> Scenario.withWarmUpDuration(seconds 20)
                   |> Scenario.withLoadSimulations [
                       //LoadSimulation.RampTo(copies 300, during = minutes 1)
                       //LoadSimulation.KeepConstant(copies 300, during = minutes 1)
                       LoadSimulation.InjectPerSec(copies 400, during = minutes 1)
                   ]
``` 

for now I will provide these simulations:
```fsharp
type LoadSimulation =
    | KeepConcurrentScenarios of copiesCount:int * during:TimeSpan
    | RampConcurrentScenarios of copiesCount:int * during:TimeSpan
    | InjectScenariosPerSec   of copiesCount:int * during:TimeSpan
    | RampScenariosPerSec     of copiesCount:int * during:TimeSpan
```

Current status: writing tests for the new scheduler
I hope I will release it on next week.

btw, DataFeed feature was merged recently https://github.com/PragmaticFlow/NBomber/pull/186

**Comment by AntyaDev** [comment]
Hi @gunmaden 
I add load simulations support
https://github.com/PragmaticFlow/NBomber/commit/5b90089c0154ef10b4f5db84956eb63c815971f5

I am testing it now but it seems it works
