### ISSUE TITLE
Question: Difference between Real-time statistics and final statistics

### ISSUE THREAD

**Issue by CamilBouzidi** [PragmaticFlow/NBomber#171]
Hello @AntyaDev ,

I hope that you are doing well. NBomber is awesome! It's been helping me a lot and can be very easily integrated into my project.

- I do have some questions about stats collection. It seems that, for real time stats, you collect statistics every 5 seconds. Is that correct? Knowing how the stats are collected would really help me. For the RPS, for example, will the value shown in real time be:

1. the last value recorded for RPS (ex: over 5 seconds, 1, 2, 3, 6, 8 were recorded, and 8 is sent as a stat),
2. the average over the last 5 seconds (ex: over 5 seconds, 1, 2, 3, 6, 8 were recorded, and the average of these, which is 5, is sent as a stat),
3. the average so far (ex: before the current 5 seconds, the average was 4, and a new average is calculated based on the previous data + the last 5 seconds),
4. Or something entirely different (or a mix of the previous options)

- I also had a question about the accuracy of the real-time statistics, especially for the RPS. There seems to be a roughly 15% difference between the real time RPS and the final RPS that appears when operation = complete. Is this because of the 5 second-collection? How do you think that I could make the results match up correctly? Btw, the operation=bombing stats is always the accurate one.

Once again, thank you so much for the amazing framework!

**Comment by AntyaDev** [comment]
Hi @CamilBouzidi 

Thank you for a so great feedback, your questions are really driving the design/features of NBomber, it's cool! Yes, you are right regarding stats and how they derived. The mechanism is quite simple it just reruns the whole stats calculation every 5 sec. Regarding RPS value it's a real-time value calculated every 5 sec.

Regarding results, I have some suspicious but it requires some investigation. I must admit that I also noticed some difference between "complete" and "realtime" values. I will try to investigate it.

Are you running NBomber as a cluster?

**Comment by CamilBouzidi** [comment]
Hey @AntyaDev

Thank you for your answer! I was thinking that it could be a good idea to let the user choose how often the stats are recalculated and how often they are to be pushed in InfluxDb? Perhaps that could help the stats be closer.

And, as of right now, I'm not using NBomber as a cluster! I will keep an eye on the feature though :)

**Comment by CamilBouzidi** [comment]
Hello @AntyaDev ,

Are there any updates on a potential bug fix, or is this issue much deeper than anticipated?

Keep up the good work, it is greatly appreciated :)

**Comment by AntyaDev** [comment]
Hi @CamilBouzidi 
Unfortunatelly no, I am very busy at my current job.
Will try to find some time on this weekend but not garantee.

**Comment by AntyaDev** [comment]
configurable stats interval is supported in v2
