### ISSUE TITLE
Scenario duration is not consistent with actual duration

### ISSUE THREAD

**Issue by zalavari** [PragmaticFlow/NBomber#172]
Hi!

I was searching for an alternative to Visual Studio LoadTest project, but I have not found good solution, except for this project.
So I tried out your solution, and I was very happy that it is very simple and easy to use. It is easy to integrate to our solution, (replace VS loadtest) and general enough to serve our needs. There is a lack of features, but the core features are all implemented.

However, I found some stability issues, and I'm not sure what causes them. (I'm using 0.15, I've seen that you have new commits, maybe you are aware some of the issues, since my problems might be related to #171 )

My first discovery was, that duration is often longer, than defined and tests are also executed after the predefined time.

I configured a test to run for 17 hours. After 16.5 hours I noticed, that the progress bar and the percentage on the console is significantly less, than it should be.
![NBomber progress](https://user-images.githubusercontent.com/43651931/69633848-4a1c8580-1051-11ea-9c7c-9367fe6e4d73.PNG)

Then I waited for some time, but test execution continued even after 17 hours.  Still waiting, and after about 17.5 hours reports are generated. The progress bar and timer still increasing on console. Tests are no longer running.  I am not even sure, whether the additional tests are included in the statistics or not.
![NBomber overtime](https://user-images.githubusercontent.com/43651931/69633873-599bce80-1051-11ea-9aca-564303fff0d1.PNG)

I tried to investigate this. I configured 4 scenarios with 20 minutes duration. The tests were running for about 40 minutes. What is interesting, that one of the scenarios, started to run only after 20 minutes, so after the "official" duration, and executed tests for about another 20 minutes. They were also included in the report, at the end of the test execution (at least most of them).
I am totally at a loss, I don't even know whats going on. How can I trust the test results after this?
 
I'm also puzzled, how the scenarios and concurrent copies are distributed between threads. I started a load test, and I analyzed which tests are executed. I found out that in the beginning, only one thread will work, and execute the first scenario's first concurrent copy's sequence. Then the second copy's sequence, and so on... So I have to wait multiple minutes for the other scenarios and threads to start. In the beginning nothing seems to run parallel, and overall only one or two threads are running tests actively. (The VS loadtest starts dozens of threads immediately after starting, so can utilize the client side resources better.)

**Comment by AntyaDev** [comment]
Hi @zalavari 

Can you please share your test scenario?

**Comment by zalavari** [comment]
Ooof, I found out, that there was a `Task.Wait()` instead of `await Task` in the class, my tests were using for network communication. So the threads were synchronously waiting for the HTTP requests. I fixed it, so now the test execution looks much more better. (It's interesting, that the VS loadtest used to start dozens of threads, so we have not noticed this problem earlier.)

However, the progress bar is still inconsistent with the duration time. I will report, if I can create some minimal and reproducible test scenarios.

**Comment by zalavari** [comment]
OK, so it seems, that the framework can't really handle, if the amount of time, taken by generation of the message I want to send, can be compared to the time, taken by network communication.
So a rough example would be, that each test steps do some preparation (synchronously) for 0.2 sec, and then communicates with the server (asynchronously) for 0.8 sec.
I created a simple scenario based on this, and I attach the code and the results as well.

```
class NBExample
{
    private static Microsoft.Extensions.Logging.ILogger Logger;

    public void Run()
    {
        Logger = new LoggerFactory().AddSerilog(
        new LoggerConfiguration()
        .MinimumLevel.Debug()
        .WriteTo.File(path: ("SeriLogs\\LPT.log"))
            .CreateLogger()
        ).CreateLogger("LoadTestLogger");

        List<IStep> steps = new List<IStep>();
       
        steps.Add(Step.Create("step1", async context =>
        {
            Logger.LogInformation(CreateLogMessage(context.CorrelationId, "step1", "starting"));
            prepareMessage();
            await sendMessage();
            Logger.LogInformation(CreateLogMessage(context.CorrelationId, "step1", "finished"));
            return Response.Ok();
        }));

        steps.Add(Step.Create("step2", async context =>
        {
            Logger.LogInformation(CreateLogMessage(context.CorrelationId, "step2", "starting"));
            prepareMessage();
            await sendMessage();
            Logger.LogInformation(CreateLogMessage(context.CorrelationId, "step2", "finished"));
            return Response.Ok();
        }));
     
        var scenario = ScenarioBuilder.CreateScenario("Scenario1", steps.ToArray())
            .WithDuration(TimeSpan.FromSeconds(60))
            .WithOutWarmUp()
            .WithConcurrentCopies(100)
            ;

        NBomberRunner.RegisterScenarios(scenario).RunInConsole();
    }

    private string CreateLogMessage(string correlationId, string stepName, string state)
    {
        var ids = correlationId.Split("_");
        var userId = int.Parse(ids[ids.Length - 1]);
        var scenarioName = correlationId.Substring(0,correlationId.LastIndexOf("_"));
        var threadId = Thread.CurrentThread.ManagedThreadId.ToString();
        return $"[Thread: {threadId}], [Scenario: {scenarioName}], [User: {userId}], [Step: {stepName}], [State: {state}]";
    }
	
	//Simulates preparing a message
    private void prepareMessage()
    {
        Task.Delay(TimeSpan.FromSeconds(0.2)).Wait();
    }
	
	//Simulates sending a message
    private async Task sendMessage()
    {
        await Task.Delay(TimeSpan.FromSeconds(0.8));
    }

}
```

First, you can see, that the progress bar does not really match up with the timer.
![NBomber_58_60](https://user-images.githubusercontent.com/43651931/69733726-195e4e00-112e-11ea-8411-7a4c32160da6.PNG)

And then after completion, this is the result.
![NB_Result](https://user-images.githubusercontent.com/43651931/69733755-25e2a680-112e-11ea-9ede-589bb85cfcd6.PNG)

Here's my brief deduction:
Looking at the results, one can tell, that the avg. duration of a test sequence was about 2.3 seconds (1.124+1.171). (It should be about 2 seconds, I guess it's higher, because of the thread blocks.) The test sequence completed fewer than 1400 times, and I had 100 concurrent copies, so I can assume, that during the 1 minute duration, one copy was running for about 14*2.3=32.2 seconds in average. This is definitely less, than the expected 1 minute.
BUT, the test execution was continued after the one minute, I can tell it from my custom logs, and the logs on the console. From my logs, I could also deduce, that my scenarios were executed about 2800 times altogether. (In the first minute about 1400 times, these are also included in the stats, and after the duration again approximately 1400 times.) So with these additional tests, I get quite close to the desired 1 minute duration, but for that one minute running, my tests just need more time, because of the actively working threads.

**Comment by AntyaDev** [comment]
Hi @zalavari 

Excuse me for being inactive for a long period of time. For some reason, I haven't noticed your last comment. (next time please do not hesitate and ping me)
I am preparing a new version 0.16.0 with some new features which I think you will like.
Also, I will take a look at your example and will try to reproduce and fix it.

Thank you so much!

**Comment by zalavari** [comment]
No problem, I was also involved with other stuff.
Thank you for you hard work.
