### ISSUE TITLE
[Q] It is possible to share data btw steps using context ? 

### ISSUE THREAD

**Issue by goblinmaks** [PragmaticFlow/NBomber#173]
I have situation when need to compare data in WebSocket response to data with request. 

            var sendMessageStep = Step.Create("send message", async context =>
            {
                context.Data = Guid.NewGuid();
                await Task.Run(()=> context.Connection.SendMessage(context.Data.ToString()));
                return Response.Ok();
            },
            pool: webSocketsPool, doNotTrack: true);
           var getMessageStep = Step.Create("getMessageStep", async context =>
            {
                while (context.Connection.GetMessages().Contains(context.Data.ToString())
                {                 
                }
                return Response.Ok();
            }, 
            pool: webSocketsPool);

**Comment by AntyaDev** [comment]
Hi @goblinmaks,

You can pass data between steps via context.Data property. For example you want to return some data from step1 to step2.
In step 1 you should do the following
return Response.Ok(customData);

now in step 2 your customData will be available via:
context.Data
