### ISSUE TITLE
Could not read CustomSettings

### ISSUE THREAD

**Issue by jbergens** [PragmaticFlow/NBomber#174]
I tried to add CustomSettings to our config file and the file is parsed but the CustomSettings property is set to None.

Do you have any examples of how to use CustomSettings?

**Comment by AntyaDev** [comment]
Hi @jbergens 

Yes, I have a test for it:
https://github.com/PragmaticFlow/NBomber/blob/dev/tests/NBomber.IntegrationTests/ClusterTests.fs#L218

**Comment by jbergens** [comment]
> Hi @jbergens
> 
> Yes, I have a test for it:
> >https://github.com/PragmaticFlow/NBomber/blob/dev/tests/NBomber.IntegrationTests/ClusterTests.fs#L218

Thank you!
I took a quick look but couldn't see any parsing of the config. It just passed the config object to ClusterCoordinator.RunSession(). My thought was that it should be possible to use the config file and add the CustomSettings parts and get that parsed into some generic object or an object of a specified class.

**Comment by AntyaDev** [comment]
Hi @jbergens 
Can you post your example.

In that test I actually define soe simple json 
https://github.com/PragmaticFlow/NBomber/blob/dev/tests/NBomber.IntegrationTests/ClusterTests.fs#L229
and then pass it to agents via coordinator and check that agents received it.

You also can find working example here
https://github.com/PragmaticFlow/NBomber/blob/dev/examples/CSharp/CSharp.Examples.Cluster/Tests/MqttReqResponse/MqttReqResponseScenario.cs#L60

**Comment by jbergens** [comment]
I will try to create an example. What I want is to make a call to the config file parser and make sure the result contains the custom values.
