### ISSUE TITLE
NBomber.Sinks.InfluxDB keeps repoting already finished scenarios

### ISSUE THREAD

**Issue by dannysilence** [PragmaticFlow/NBomber#177]
Consider having NBomber with NUnit tests, mainly replciating the following structure:

```csharp
public class Tests
{
    public IReportingSink Sink { get; } = new InfluxDbSink("http://localhost:8086", "nbomber");

    [Test]
    public void Test1()
    {
        var scenario = ScenarioBuilder.CreateScenario(/* some actual test logic here */);

        NBomberRunner
            .RegisterScenario("Test1", scenario)
            .WithReportingSinks(new[]{ Sink }, TimeSpan.FromSeconds(10))
            .RunTest();
    }

    [Test]
    public void Test2()
    {
        var scenario = ScenarioBuilder.CreateScenario(/* some actual test logic here */);

        NBomberRunner
            .RegisterScenario("Test2", scenario)
            .WithReportingSinks(new[]{ Sink }, TimeSpan.FromSeconds(10))
            .RunTest();
    }
}
```

Next start running the tests not in a parallel mode.

While Test1 is running its statistical data appears on the graphs.
After the Test1 finished and Test2 starts, data from both tests starts appearing.
As a result final graph lines are interfering, however they should not interfere, as tests were executed sequentially and not in parallel.

We see erroneous results on the following graph lines (notice, all tests executed not in parallel):
![image](https://user-images.githubusercontent.com/48093199/72239887-1985b080-35eb-11ea-8ae0-716dae7f7e4d.png)
![image](https://user-images.githubusercontent.com/48093199/72239901-2a362680-35eb-11ea-822c-3f42e51ab9b5.png)

**Comment by AntyaDev** [comment]
Hi @dannysilence 

I have tried but I can't reproduce it.
