### ISSUE TITLE
NBomber.Sinks.InfluxDB has gaps in a reported metrics

### ISSUE THREAD

**Issue by dannysilence** [PragmaticFlow/NBomber#179]
The screenshot shows a single launch of 10 min tests. As you can see from the screen, there are some gaps in reported values: ![image](https://user-images.githubusercontent.com/48093199/72537136-40aadf00-3884-11ea-97b8-30238f5bb61e.png)

**Comment by AntyaDev** [comment]
Hi @dannysilence 
How I can reproduce it?
and what the metric are you displaying - RPS ?

**Comment by AntyaDev** [comment]
Hi @dannysilence 
I think can happen if you put in response some big obj since we don't have a compaction process.
I think it could be fixed by Step Compaction process
I will start work on it soon.

**Comment by dannysilence** [comment]
Thanks!
