### ISSUE TITLE
Add custom step function with customized time measurement

### ISSUE THREAD

**Issue by vilinski** [PragmaticFlow/NBomber#183]
Currently it is not possible to provide a custom step `execute` function where one can exactly define where the step measurement starts and ends.
Scenarios: 
- some calls like request preparation and response interpretation should not be involved in the time measuremnet. 
- when `start` and `end` times are coming from different routines, like sending request to one queue, waiting for the answer from the other queue, not necessarily the same.

**Comment by AntyaDev** [comment]
Hi @vilinski 
with Nbomber 1.0.0 you can set custom latency
https://github.com/PragmaticFlow/NBomber/blob/dev/src/NBomber/Contracts.fs#L149

I know it's not exactly what you need, but probably it can be helpful
