### ISSUE TITLE
Another Newbie Question - C# RunTest() method is void when using Nuget package

### ISSUE THREAD

**Issue by LyolikHL** [PragmaticFlow/NBomber#184]
Hello. First, thanks a lot for the framework. We've just started testing it, but looks like it can meet all our needs.

I have been playing around with the 0.16.0 version lately. Initially I added NBomber project to my solution manually and was referencing it locally (`Include="..\..\..\src\NBomber\NBomber.fsproj`). I followed the C# NUnit example, where the load tests stats are assigned to a variable: 
`var allStats = NBomberRunner.RegisterScenarios(scenario).RunTest();`
It was working as expected and I could use the statistics for NUnit assertions.

Then I installed the Nuget package and now in the NBomberRunner class from metadata I can see the following:
```
#region Assembly NBomber, Version=0.16.0.0, Culture=neutral, PublicKeyToken=null
// C:\Users\User\.nuget\packages\nbomber\0.16.0\lib\netstandard2.0\NBomber.dll
#endregion

...

namespace NBomber.CSharp
{
    [CompilationMapping(SourceConstructFlags.ObjectType)]
    public class NBomberRunner
    {
        public static TestContext LoadInfraConfig(this TestContext context, string path);
        public static TestContext LoadTestConfig(this TestContext context, string path);
        public static TestContext RegisterScenarios(params Scenario[] scenarios);
        public static void Run(this TestContext context);
        public static void RunInConsole(this TestContext context);
        public static void RunTest(this TestContext context);
        ...
    }
}
```

As you can see RunTest() method is void now.
Any ideas what could be the reason?

Thanks in advance )

**Comment by AntyaDev** [comment]
Hi @LyolikHL 
Oh, I see, it's probably my fault :)
Sorry, will publish patch today

**Comment by AntyaDev** [comment]
Hi @LyolikHL 
I think you mixed something at least what I see that v0.16.0 is using a different approach for writing asserts via Assert.forStep
In a new version v0.17.0 (which is currently in development) we will drop this and replace it with just returning stats to the users.
