### ISSUE TITLE
Improvement Request: WarmUp phase to be parallel

### ISSUE THREAD

**Issue by dannysilence** [PragmaticFlow/NBomber#185]
Currently the warm up phase is being executed sequentially, so if we have 10 scenarios and configured 1 minute warm up, the overall warming up will take 10 minutes. 

That is a bit misaligned with the actual scenarios execution, where all scenarios are executed in parallel.

Can you please either update the warm up to be parallel, or provide the ability to configure such behavior?

**Comment by AntyaDev** [comment]
Hi @dannysilence 
it was added in beta 1.0.0
