### ISSUE TITLE
Огромная потеря производительности, почему?

### ISSUE THREAD

**Issue by BashkaMen** [PragmaticFlow/NBomber#187]
Я тестировал один и тот же код двумя вариантами и получил колоссально разные результаты.
Обрати внимание на Request count
2717669 против 13430260

```
        private Scenario CreateScenario(string name, IStep[] steps)
        {
            var scenario = ScenarioBuilder.CreateScenario(name, steps)
                .WithConcurrentCopies(1)
                .WithWarmUpDuration(TimeSpan.FromSeconds(1))
                .WithDuration(TimeSpan.FromSeconds(10));

            return scenario;
        }
    

        [Test]
        public void Query()
        {
            var query = new BoolQuery();
            
            var step = Step.Create("QueryAsync", async context =>
            {
                await _queryBus.QueryAsync(query);
                return Response.Ok();
            });

            var scenario = CreateScenario("Query performance", new[] {step});
            
            NBomberRunner.RegisterScenarios(scenario).RunTest();
        }
```
Nbomber выдал такую статистику:

```
[17:30:49 INF] scenario: 'Query performance', duration: '00:00:10', RPS: '271766', concurrent Copies: '1'
+----------------------------+----------------------------------------------+
| step                       | details                                      |
+----------------------------+----------------------------------------------+
| - name                     | QueryAsync                                   |
+----------------------------+----------------------------------------------+
| - request count            | all = 2717669 | OK = 2717669 | failed = 0    |
+----------------------------+----------------------------------------------+
| - response time            | RPS = 271766 | min = 0 | mean = 0 | max = 10 |
+----------------------------+----------------------------------------------+
| - response time percentile | 50% = 1 | 75% = 1 | 95% = 2 | StdDev = 1     |
+----------------------------+----------------------------------------------+
| - data transfer            | min = - | mean = - | max = - | all = -       |
+----------------------------+----------------------------------------------+
```
И второй вариант, мануальный

```
        [Test]
        public async Task ManualQuery()
        {
            var token = new CancellationTokenSource();
            var query = new BoolQuery();
            var count = 0;

            token.Token.Register(() => TestContext.WriteLine($"Query handled {count} per 10 sec"));
            token.CancelAfter(TimeSpan.FromSeconds(10));
            
            while (!token.IsCancellationRequested)
            {
                await _queryBus.QueryAsync(query);
                count++;
            }
        }
```

`Query handled 13430260 per 10 sec`

Есть подозрение что бомбер меряет все время работы сценария вместе с операциями самого бомбера, а по идее нужно трекать время только моей лямбды и суммировать.

**Comment by AntyaDev** [comment]
@BashkaMen 
NBomber меряет выполнение лямбы.
а можешь плиз попробовать с Http, попробуй любой веб сервер побомбить чтобы летенси реальная была

**Comment by BashkaMen** [comment]
@AntyaDev хорошо, завтра кину результаты.

**Comment by BashkaMen** [comment]
Код в лямбде
`await _http.GetAsync("https://jsonplaceholder.typicode.com/posts/1");`
Бомбер:` | - request count            | all = 1449 | OK = 1449 | failed = 0        |`
Мануально: `Query handled 1435 per 10 sec`

**Comment by AntyaDev** [comment]
Там есть минимум 2 ньюанса с твоим примером:
- Task.Delay неточный, погрешность может достигать до 100-200мс. Так как у тебя там почти нет летенси это легко может привести к тем расхождениям. Nbomber например умеет это хендлит, он все неточности потом обрезает 
- NBomber имеет шедулер который мониторит таски и запускает их по-новому. Ещё Nbomber ведёт подсчет статистики и это требует ресурсов как CPU так и RAM.

Тут поинт больше понимать что ты тестишь что-то реальное, с реальной летенси а не то что ты привел где летенси 0

**Comment by BashkaMen** [comment]
Я хотел потестить пропускную способность своей либы, дабы понимать как быстро она резолвит хендлер на кверю, но спасибо, бомбером покрою реальный запрос своей приложухи :)

**Comment by AntyaDev** [comment]
Для таких нужд советую заюзать BenchmarNet. Он тебе покажет сколько например RAM выделяется при каждом инвокейшене
