### ISSUE TITLE
HttpStep.Create problem with StepContext

### ISSUE THREAD

**Issue by bper19** [PragmaticFlow/NBomber#198]
Upon using HttpStep.Create(), the following error appears:

> Reference to type 'StepContext<,>' claims it is defined in 'NBomber', but it could not be found.

NBomber v1.0.0-beta4
NBomber.Http v1.0.0-beta3

**Comment by AntyaDev** [comment]
Hi @bper19 ,
I will take a look...

**Comment by AntyaDev** [comment]
Hi @bper19 ,
Can you try latest beta5?

**Comment by MaheshGooner** [comment]
still doesn't work with beta5 or  rc

**Comment by AntyaDev** [comment]
Hi @MaheshGooner 
can you please look at examples?
https://github.com/PragmaticFlow/NBomber/blob/dev/examples/CSharp/CSharp.Examples/Scenarios/Http.cs

**Comment by AntyaDev** [comment]
Hi @bper19 , @MaheshGooner is it resolved?

**Comment by MaheshGooner** [comment]
Hey @AntyaDev. I had a missing dependency for NBomber.Http. after i added that it works well. I was keen on an rabbitmq example, do you have one ?

**Comment by bper19** [comment]
This works now. Sorry for the late response.

**Comment by AntyaDev** [comment]
@MaheshGooner yes, it's what we call PUSH scenario. I am writing docs about this now and later will add some examples.

**Comment by MaheshGooner** [comment]
@AntyaDev Awesome. that would be great. do you when you would be done with the Docs ?
