### ISSUE TITLE
Success counts calculated by the NBomber and by the code do not match

### ISSUE THREAD

**Issue by crack-design** [PragmaticFlow/NBomber#208]
I'm using NBomber to run single scenario as my load test. 
With the following scenario(CreateImmediateJob is my executing Func):
`var scenario =
                BuildScenario("Create", "CreateImmediateJob", CreateImmediateJob)
                    .WithLoadSimulations(new[]
                    {
                        Simulation.InjectScenariosPerSec(1, TimeSpan.FromMinutes(5)),
                    });`
And running it like this:
`var nodeStats = NBomberRunner
                .RegisterScenarios(new[] { scenario })
                .RunTest();`
I expected there to be issued 300 requests (1 * 60 * 5). 
In the results I have decent deviation between upper mentioned numbers and output results. 
For example sometimes I get around 260, or sometimes even less then 240 requests being tracked in results (all these are passed ones, no failures) and this amount is different every time. How do I get the exact number of requests to be executed?

**Comment by AntyaDev** [comment]
Hi @crack-design 
I will take a look

**Comment by AntyaDev** [comment]
Hi @crack-design 
tell me what version of NBomber are you using?

**Comment by crack-design** [comment]
Hey @AntyaDev , it's 1.0.0-beta4

**Comment by crack-design** [comment]
Maybe it's worth mentioning that I tried calculating the requests manually inside my executing Func, by just incrementing the counter and the results there were very close to what I should get (~300-302). So basically looks like it issues the correct number of requests, but some of them are not counted in the final NBomber results.

**Comment by AntyaDev** [comment]
I just did a simple example:

```fsharp
    let mutable counter = 0

    let step1 = Step.create("step_1", fun context -> task {
        // you can do any logic here: go to http, websocket etc
        counter <- counter + 1
        context.Logger.Information("counter: " + counter.ToString())
        do! Task.Delay(TimeSpan.FromMinutes 10.0)
        return Response.Ok(42) // this value will be passed as response for the next step
    })

    let scenario = Scenario.create "hello_world_scenario" [step1;] //step2]
                   |> Scenario.withoutWarmUp
                   |> Scenario.withLoadSimulations [
                       InjectScenariosPerSec(copiesCount = 1, during = TimeSpan.FromMinutes 5.0)      
                   ]

    NBomberRunner.registerScenarios [scenario]
    |> NBomberRunner.runInConsole
```

and log output shows **exactly 300 requests**, but from statistics, I see: 
- request count            | all = 0 | OK = 0 | failed = 0  

I believe that scheduler works correctly: but something wrong with stats especially for this case with inject per sec.

**Comment by crack-design** [comment]
Yeah, sometimes I have the same behavior as you do, all zeroes everywhere :)

**Comment by AntyaDev** [comment]
Ah, it was my mistake.
I forgot that I am waiting and no one request is actually finished

do! Task.Delay(TimeSpan.FromMinutes 10.0)

**Comment by AntyaDev** [comment]
@crack-design try also to run on 1.0.0-beta5

**Comment by crack-design** [comment]
@AntyaDev , It does work for me the same on beta5. Here's my example Func:
```
async Task<Response> CreateAndGetJob(IStepContext<Unit, Unit> context)
            {
                var job = new Job
                {
                    Name = $"Job{++iterator}",
                    PayLoad = JsonConvert.SerializeObject(new SampleProcessServicePayload
                    {
                        Delay = TestRunConfig.JobDurationInSeconds,
                        IsInner = true,
                        JobRequestsRetry = false,
                        ThrowException = false
                    }),
                };
                var createJobResponse = await WebApiClient.CreateJob(job);

                if (createJobResponse.responseMessage.StatusCode != HttpStatusCode.Created)
                {
                    Interlocked.Increment(ref failedCount);
                    return Response.Fail("Error creating a job");
                }

                await ReceivedNotificationsDispatcher.SubscribeAndWaitForCompletion(
                    new[] { createJobResponse.job.Id },
                    WebhookType.ExecutionStateChangedProcessing);

                try
                {
                    await ReceivedNotificationsDispatcher.SubscribeAndWaitForCompletion(
                        new[] { createJobResponse.job.Id });
                }
                catch (TimeoutException)
                {
                    Interlocked.Increment(ref failedCount);
                    return Response.Fail("Timeout of 30 seconds exceeded");
                }

                Interlocked.Increment(ref passedCount);
                return Response.Ok();
            }
```

**Comment by AntyaDev** [comment]
He @crack-design how long it takes to execute your request? I mean milliseconds
It seems for me that you are doing several sequential calls which can lead to a situation that your request will take more than 1 sec. If it's true than NBomber shows correct results.

**Comment by AntyaDev** [comment]
In order to show the difference, just comment all your code and put some timer:
await Task.Delay(500)

**Comment by crack-design** [comment]
It definitely takes more than one second. On average about 5-6 seconds. I think I then just might misunderstood about how I should properly set up the load.

**Comment by AntyaDev** [comment]
Look, the step will be count only in case it finished.
In your case you do the following:
1. you ask NBomber to send 300 requests(steps) in 5 min.
2. but the catch here is that your 300 steps will not be finished in 5 minutes because 1 step takes more than 1 sec. So it basically your server was not able to handle 300 requests in 5 minutes, it handled 240-260 but not 300.

**Comment by crack-design** [comment]
Okay, I see now. Thank you for the exhaustive answer.
