### ISSUE TITLE
Disable reports generation

### ISSUE THREAD

**Issue by lkurzyniec** [PragmaticFlow/NBomber#212]
Is there a way to disable reports generation?

Enum `ReportFormat` do not contain `None`.
There is no method like `WithoutReports()`.

**Comment by AntyaDev** [comment]
Hi @lkurzyniec ,
I think that you can specify an empty array  WithReportFormats().
I will consider adding extension WithoutReports().

**Comment by lkurzyniec** [comment]
Unfortunately, it doesn't work. I have tried both `.WithReportFormats()` and `.WithReportFormats(new ReportFormat[0])`, but still NBomber produce reports.
