### ISSUE TITLE
Cluster Sample does not exist anymore

### ISSUE THREAD

**Issue by tim1993** [PragmaticFlow/NBomber#219]
The link of the example for cluster support in your README doesn't exist anymore.
I'm very interested in Cluster support for load testing, so what is the recommended way to get cluster support with NBomber? Is it to run parallel tests with NUnit? Can you please describe or fix the example?

**Comment by AntyaDev** [comment]
Hi @tim1993 
We decided to rethink and refactor cluster therefore it was dropped

**Comment by tim1993** [comment]
Thanks for your quick reply @AntyaDev.
I'm still interested in how to run a scenario in cluster mode with the current C# implementation but can't get it running with provided documentation / samples.

Do you have still the sample code and can you provide it here in the issue?
Many thanks in advance, good work ;)
