### ISSUE TITLE
Feature request: configurable percentiles

### ISSUE THREAD

**Issue by charleskorn-x** [PragmaticFlow/NBomber#222]
It would be great if I could specify the latency percentiles to report on - at the moment, they seem hard coded (as 50th, 75th and 90th perecentiles).

In my particular situation, I'm interested in the 99th and 99.9th percentiles, but I can imagine it would be helpful for these to be configurable.

**Comment by charleskorn-x** [comment]
Hi @AntyaDev, Gatling is one example.

**Comment by AntyaDev** [comment]
@charleskorn-x any links to check how they express it via API?

**Comment by AntyaDev** [comment]
@charleskorn-x  any updates?

**Comment by charleskorn-x** [comment]
Sorry for the slow response @AntyaDev. In the configuration file, you can specify four percentiles you are interested in: https://github.com/gatling/gatling/blob/master/gatling-core/src/main/resources/gatling-defaults.conf#L82

**Comment by AntyaDev** [comment]
@charleskorn-x thanks. I will try to add it after I finish updating the documentation.
