### ISSUE TITLE
Package not found when NuGet is a provider

### ISSUE THREAD

**Issue by adrian-lewis-load-test** [PragmaticFlow/NBomber#223]
Forgive my ignorance, but I am completely new to the ,Net world and only recently started to use Windows!

I attempt to install the nbomber package as admin:

```
PS C:\Windows\System32> Install-Package NBomber
```
However, I receive a:

```
Install-Package: No match was found for the specified search criteria and package name 'NBomber'....
```

But when I do **Get-PackageSource**, **NuGet** is clearly present. 
```PS C:\Windows\System32> Get-PackageSource

Name                             ProviderName     IsTrusted  Location
----                             ------------     ---------  --------
MyNuGet                          NuGet            False      https://api.nuget.org/v3/index.json
PSGallery                        PowerShellGet    False      https://www.powershellgallery.com/api/v2
```

And I am not sure what the issue is here?

**Comment by vilinski** [comment]
you may also check out .NET [command line tools.](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet) Try this in your project folder:

`dotnet add package NBomber`

**Comment by AntyaDev** [comment]
dotnet add package NBombe --version=1.0.0-rc

**Comment by adrian-lewis-load-test** [comment]
Thanks
