### ISSUE TITLE
Count mismatch during a ramp

### ISSUE THREAD

**Issue by MaheshGooner** [PragmaticFlow/NBomber#227]
I have the following scenario

```
public void amqpPublish()
        {
Scenario BuildScenario()
        {
            var step = Step.Create("amqp step", async context =>
            {
                await Task.Delay(TimeSpan.FromSeconds(0.1));
                publishRequest();
                return Response.Ok(sizeBytes: 1024);
            });

            return ScenarioBuilder.CreateScenario("amqp publish", step);
        }


            var scenario = BuildScenario()
                .WithoutWarmUp()
                .WithLoadSimulations(new[]
                {
                    Simulation.RampScenariosPerSec(copiesCount: 5, during: TimeSpan.FromSeconds(10))
                });

            var pingPluginConfig = PingPluginConfig.CreateDefault(new[] { "rabbit_mq" });
            var pingPlugin = new PingPlugin(pingPluginConfig);

            NBomberRunner
                .RegisterScenarios(scenario)
                .WithPlugins(pingPlugin)
                .Run();
        }
```
I am expecting total of 5 requests ramp up during 10 seconds. but the html report suggests i have 20 for some reason.
![image](https://user-images.githubusercontent.com/18375888/86766697-cd1fa880-c042-11ea-99f5-7fbb3c398700.png)

**Comment by MaheshGooner** [comment]
Also noticed there were not requests recoreded when i did `Simulation.InjectScenariosPerSec(copiesCount: 5, during: TimeSpan.FromSeconds(2))`

![image](https://user-images.githubusercontent.com/18375888/86767397-d8bf9f00-c043-11ea-9882-16fd772a0176.png)

But if i increase the time duration to like 10 seconds it records fine.

**Comment by AntyaDev** [comment]
Hi @MaheshGooner 
> RampScenariosPerSec(copiesCount: 5, during: TimeSpan.FromSeconds(10)) 

it's injecting copies every second until it reaches 5 concurrent copies per second.
for example, on 1 sec it injects only 1 copy. on the fifth second, it injects 2 copies. (basically, it smoothly increase the load every second)

On the other hand, I think that your idea was not to increase but stretch load on a specified duration. Is it correct?
Basically you wanna set some request count and say - please send in total 5 requests in 10 seconds?

> Also noticed there were not requests recoreded when i did Simulation.InjectScenariosPerSec(copiesCount: 5, during: TimeSpan.FromSeconds(2))

I think NBomber has validation rules to prevent running scenario with a duration less than 10.

**Comment by AntyaDev** [comment]
When it comes to load simulation, systems behave in 2 different ways:
- Closed systems, where you keep a constant number of concurrent clients and they waiting on a response before sending a new request. A good example will be a database with 20 concurrent clients that constantly repeat sending query then wait for a response and do it again. Under the big load, requests will be queued and this queue will not grow since we have a finite number of clients
- Open systems, where you keep arrival rate of new clients requests without waitng on responses. The good example could be some popular website like Amazon. Under the load new clients will arriving even though applications have trouble serving them.

Make sure to use the proper load model that matches the load of your system. NBomber provides such types:

```fsharp
type LoadSimulation =
    /// for closed system
    | RampConcurrentScenarios of copiesCount:int * during:TimeSpan
    | KeepConcurrentScenarios of copiesCount:int * during:TimeSpan

    /// for open system
    | RampScenariosPerSec     of copiesCount:int * during:TimeSpan
    | InjectScenariosPerSec   of copiesCount:int * during:TimeSpan
```

**Comment by MaheshGooner** [comment]
> Hi @MaheshGooner
> 
> > RampScenariosPerSec(copiesCount: 5, during: TimeSpan.FromSeconds(10))
> 
> it's injecting copies every second until it reaches 5 concurrent copies per second.
> for example, on 1 sec it injects only 1 copy. on the fifth second, it injects 2 copies. (basically, it smoothly increase the load every second)
> 
> On the other hand, I think that your idea was not to increase but stretch load on a specified duration. Is it correct?
> Basically you wanna set some request count and say - please send in total 5 requests in 10 seconds?
> it could be something like **InjectTotalScenarios(copiesCount: 5, during: TimeSpan.FromSeconds(10))**
> 
> > Also noticed there were not requests recoreded when i did Simulation.InjectScenariosPerSec(copiesCount: 5, during: TimeSpan.FromSeconds(2))
> 
> I think NBomber has validation rules to prevent running scenario with a duration less than 10.



> Hi @MaheshGooner
> 
> > RampScenariosPerSec(copiesCount: 5, during: TimeSpan.FromSeconds(10))
> 
> it's injecting copies every second until it reaches 5 concurrent copies per second.
> for example, on 1 sec it injects only 1 copy. on the fifth second, it injects 2 copies. (basically, it smoothly increase the load every second)
> 
> On the other hand, I think that your idea was not to increase but stretch load on a specified duration. Is it correct?
> Basically you wanna set some request count and say - please send in total 5 requests in 10 seconds?
> it could be something like **InjectTotalScenarios(copiesCount: 5, during: TimeSpan.FromSeconds(10))**
> 
> > Also noticed there were not requests recoreded when i did Simulation.InjectScenariosPerSec(copiesCount: 5, during: TimeSpan.FromSeconds(2))
> 
> I think NBomber has validation rules to prevent running scenario with a duration less than 10.

Yeah i would be looking for something like this `InjectTotalScenarios(copiesCount: 5, during: TimeSpan.FromSeconds(10))` where i could introduce load in a linear manner, is there a way i could achieve this ? I see currently there are 4 load simulation models for NBomber.

Having different simulation models would be very useful i think not sure if Nbomber currently supports few things like gatling [here](https://gatling.io/docs/current/general/simulation_setup#open-model). if not it could be a useful feature.

**Comment by AntyaDev** [comment]
InjectTotalScenarios - is in my TOP priority after the release of version 1. I am working on documentation now (I hope in 2 weeks I will release v1)

NBomber has 4 most important simulation types: 
```fsharp
    /// For closed system:
    /// Injects a given number of scenario copies 
    /// with a linear ramp over a given duration.
    /// Use it for ramp up and rump down.
    RampConcurrentScenarios(copiesCount = 10, during = seconds 30)

    /// For closed system:
    /// Injects a given number of scenario copies 
    /// at once and keep them running, during a given duration. 
    KeepConcurrentScenarios(copiesCount = 10, during = seconds 30)

    /// For open system:
    /// Injects a given number of scenario copies 
    /// from starting rate to target rate, 
    /// defined in scenarios per second, during a given duration. 
    RampScenariosPerSec(copiesCount = 10, during = seconds 30)

    /// For open system:
    /// Injects a given number of scenario copies at a constant rate, 
    /// defined in scenarios per second, during a given duration. 
    InjectScenariosPerSec(copiesCount = 10, during = seconds 30)
```

**Comment by AntyaDev** [comment]
@MaheshGooner what you are testing? API server, database, pub sub message broker?

**Comment by MaheshGooner** [comment]
That would be great 👍. I'm testing rabbitmq.

**Comment by AntyaDev** [comment]
Closed this and opened a new one https://github.com/PragmaticFlow/NBomber/issues/229
