### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by MaheshGooner** [PragmaticFlow/NBomber#228]
Not that it's affecting anyone but may be in your next release you might want to fix it.

![image](https://user-images.githubusercontent.com/18375888/86806885-3ae2c900-c071-11ea-927f-6d9a74be855e.png)

**Comment by MaheshGooner** [comment]
one more 
![image](https://user-images.githubusercontent.com/18375888/86807565-e3912880-c071-11ea-8e6a-71af14ed8290.png)

**Comment by AntyaDev** [comment]
thanks a lot @MaheshGooner 
I will fix it after documentation.

**Comment by AntyaDev** [comment]
Hi @MaheshGooner 
I have fixed those issues.
I started working on the new docs https://nbomber.com/docs/
It's a very very raw draft

**Comment by ManiRadhakrishnan** [comment]
@AntyaDev may be you can close this. Any chance of seeing documentation on how to run in a distributed cluster anytime soon ? I know you might be working on your spare time :)
