### ISSUE TITLE
Add StepIteration (or something like this) to the CorrelationId type

### ISSUE THREAD

**Issue by darraghjones** [PragmaticFlow/NBomber#230]
I want to create my own IFeed which returns the same FeedItem for each 'iteration'.

So Simulation.InjectScenariosPerSec(10, TimeSpan.FromSeconds(10)) would send 10 identical requests in the first second, then a different batch of identical 10 requests, etc.

If there was a StepIteration property on the CorrelationId, I believe I could create my feed object similar to the constant feed, but replace the CopyNumber with this property...something like:

`T IFeed<T>.GetNextItem(CorrelationId correlationId, IDictionary<string, object> stepData) => this.allItems[correlationId.StepIteration % this.allItems.Length];
`

Please let me know if this makes sense, of if there is something already which exists I might be able to use. 
Really like the framework so far, thanks!

**Comment by AntyaDev** [comment]
Hi @darraghjones ,
Thanks for your feedback, I really appreciate it.

I got your idea, but what do you think about using Dictionary in your custom feed and count iterations?

**Comment by darraghjones** [comment]
Thanks for the response. This is the approach I've started working on. But I'm not sure I've quite understood the meaning of the `correlationId.CopyNumber` property.

I've created a simple `LoggingFeed` which I've being using to try and understand how it behaves....

        class LoggingFeed : IFeed<object>
        {
            public object GetNextItem(CorrelationId correlationId, IDictionary<string, object> stepData)
            {
                Console.WriteLine(new
                {
                    correlationId.Id,
                    correlationId.ScenarioName,
                    correlationId.CopyNumber
                });
                return null;
            }

            public string FeedName { get; }
        }

When I use this with inside the following test

       public void Run()
        {
            var feed = new LoggingFeed();
            
            var step = Step.Create("step", feed, async context =>
            {
                await Task.Delay(TimeSpan.FromSeconds(1.5));
                return Response.Ok();
            });

            var scenario = ScenarioBuilder.CreateScenario("Hello World!", step)
                 .WithoutWarmUp()
                 .WithLoadSimulations(Simulation.InjectScenariosPerSec(3, TimeSpan.FromSeconds(10)));

            NBomberRunner.RegisterScenarios(scenario).Run();
        }

I see in the output 
```
...
21:35:28 INF] starting bombing...
{ Id = Hello World!_0, ScenarioName = Hello World!, CopyNumber = 0 }
{ Id = Hello World!_1, ScenarioName = Hello World!, CopyNumber = 1 }
{ Id = Hello World!_2, ScenarioName = Hello World!, CopyNumber = 2 }
{ Id = Hello World!_3, ScenarioName = Hello World!, CopyNumber = 3 }
{ Id = Hello World!_4, ScenarioName = Hello World!, CopyNumber = 4 }
{ Id = Hello World!_5, ScenarioName = Hello World!, CopyNumber = 5 }
{ Id = Hello World!_0, ScenarioName = Hello World!, CopyNumber = 0 }
{ Id = Hello World!_1, ScenarioName = Hello World!, CopyNumber = 1 }
...
```
I don't understand why I see any log entries with CopyNumber > 2 as I've specified a copiesCount of 3 for my Simulation.
Interestingly, if I reduce the `Task.Delay(TimeSpan.FromSeconds(1.5))` to just 0.5 seconds, the logs are as expected. I.e.
```
...
21:42:40 INF] starting bombing...
{ Id = Hello World!_0, ScenarioName = Hello World!, CopyNumber = 0 }
{ Id = Hello World!_1, ScenarioName = Hello World!, CopyNumber = 1 }
{ Id = Hello World!_2, ScenarioName = Hello World!, CopyNumber = 2 }
{ Id = Hello World!_0, ScenarioName = Hello World!, CopyNumber = 0 }
{ Id = Hello World!_1, ScenarioName = Hello World!, CopyNumber = 1 }
{ Id = Hello World!_2, ScenarioName = Hello World!, CopyNumber = 2 }
{ Id = Hello World!_0, ScenarioName = Hello World!, CopyNumber = 0 }
{ Id = Hello World!_1, ScenarioName = Hello World!, CopyNumber = 1 }
...

Is this behaviour by design? 

```

**Comment by AntyaDev** [comment]
Hi @darraghjones 

First, try to use Simulation.KeepConcurrentScenarios and you will get expected results. 
Then read this subject: https://nbomber.com/docs/core-abstractions#load-simulations

I can explain what happens: because you are using InjectScenariosPerSec and Task.Delay(TimeSpan.FromSeconds(1.5) it led you to the situation that NBomber waits for 1 sec to complete the started task (but you don't, because 1.5 sec) and then because the current task wasn't completed  it will start a new one  (because you asked using InjectPerSec - meaning you specified injection rate)
Basically, if you change Task.Delay to < 1 sec NBomber should be able to reuse previously started task and your Copy Number will be the same.

In addition in NBomber v1 which soon will be released, we change naming for LoadSimulation

```fsharp
type LoadSimulation =
    | RampConstant of copies:int * during:TimeSpan
    | KeepConstant of copies:int * during:TimeSpan
    | RampPerSec   of rate:int   * during:TimeSpan
    | InjectPerSec of rate:int   * during:TimeSpan
```

Also if you are testing HTTP server/WebSite it's an open system and you should use InjectPerSec

Does it make sense?

**Comment by darraghjones** [comment]
Ok, thanks for the clarification. So it seems it's expected that the copyNumber can be greater than the number of injected copies when the step takes longer than a second and when using one of the open system loadsimulations.

**Comment by AntyaDev** [comment]
@darraghjones yes, correct. For your case, I would rather use time window semantic - just use single shared value for all of your steps and update value periodically.
