### ISSUE TITLE
RPS doesn't show in table/chart

### ISSUE THREAD

**Issue by gunmaden** [PragmaticFlow/NBomber#231]
Hi. I tried to navigate through decompiled C# code cause I'm not good in F# but can't find problem.

I have one plain scenario which perform multiple steps, but somehow RPS metrics lost and it seems like this

![img](https://user-images.githubusercontent.com/7446973/88283732-13406180-ccfd-11ea-8450-8a0a39b31bcc.png)

Could you tell what I'm possible doing wrong and possible solution?

Lang: C#
Framework: netcoreapp2.2
NBomber package version: 1.0.0-rc

**Comment by gunmaden** [comment]
Similar thing in influx sink data
![img](https://user-images.githubusercontent.com/7446973/88394411-76e78f00-cdd0-11ea-934e-002db1787fbd.png)

**Comment by AntyaDev** [comment]
Hi @gunmaden 
I will take a look on this a bit later. I guess I know what happens.

**Comment by gunmaden** [comment]
Hi @AntyaDev any news?

**Comment by gunmaden** [comment]
Answer https://github.com/PragmaticFlow/NBomber/issues/234#issuecomment-668633079
