### ISSUE TITLE
Any metric shows how many concurrent copies run?

### ISSUE THREAD

**Issue by gunmaden** [PragmaticFlow/NBomber#232]
Hi!
Is there any metric which could show how many concurrent scenarios run this moment?

This is how it's made in Yandex-Tank
![img](https://user-images.githubusercontent.com/7446973/89171864-ce38ec80-d592-11ea-9aeb-f943d2098193.png)

**Comment by AntyaDev** [comment]
Hi @gunmaden ,
We are going to add it in next or release after.

**Comment by gunmaden** [comment]
Thanks for your reply. Ok, now I use workaround with interlocked increment which can cause some perfomance reducing in first step of scenario and decrement on fail/last step of scenario

**Comment by AntyaDev** [comment]
Hi @gunmaden 
in the current 1.0.0 version, you can render LoadSimulationStats value into Grafana.
https://github.com/PragmaticFlow/NBomber/blob/dev/src/NBomber/Contracts.fs#L97
InfluxDb plugin supports it:
