### ISSUE TITLE
Is there a way to introduce constant load per specfic time interval instead of per second ?

### ISSUE THREAD

**Issue by MaheshGooner** [PragmaticFlow/NBomber#233]
I was looking for a load simulation something like "X number of users send 1 request every N seconds" and keep doing this until test reaches specific number of total users or a specfic time duration. Is there a way i could simulate this type of load ?

For example i can do this gatling with `setUp(scn.inject(splitUsers(totalusers) into atOnceUsers(X) separatedBy(N seconds))`

is there an easy way of doing this in Nbomber ?

**Comment by AntyaDev** [comment]
@MaheshGooner I think no

**Comment by AntyaDev** [comment]
Can you explain what benefit it brings compared to "per second"?

**Comment by gunmaden** [comment]
We cant set rate less than 1, so we can't make long load (such as 500/1000 threads on 50 minute)

**Comment by MaheshGooner** [comment]
> For example now we can't set rate less than 1, so we can't make long linear load (such as 500/1000 threads on 50 minute). In case when I need to increment by 1 each 6 seconds

+1. using PerSec there is a limitation for sending atleast 1 request a second. but if you want to keep a small steady load it would be good to have ability to introduce it in varied intervals(as @gunmaden's example "1 each 6 secs").

**Comment by AntyaDev** [comment]
@MaheshGooner @gunmaden 
To be honest 1 per sec (RPS) it's well-known criteria to describe the load.
I understand maybe for certain cases it's not enough

**Comment by AntyaDev** [comment]
@MaheshGooner > but if you want to keep a small steady load  
that's my problem.
When you test - you test to get max from your service/system. (all other things it's just speculation that shows you nothing)

**Comment by AntyaDev** [comment]
@gunmaden @MaheshGooner 
https://nbomber.com/docs/loadtesting-basics#what-to-measure-about-performance

**Comment by gunmaden** [comment]
I think we missunderstood each other. Let me try to explain my point.

I use NBomber as tool to load system and see which potential count of people will affect system to degrade, to determine it I use metrics from services. 

As you understood, pull load on start with large increment is not what I need. But if we have global system on which users connect with interval of timezones (ex. 11 am in London is not same time in Moscow) so sometimes we must to do continuous load over hours with little increment (ex. 1000-2000 copies per hour) in this case we can't do this without horrible hacks such as adding dynamic delay based on current copies running

So my scenario which I want to migrate from yandex tank but I can't reach now is get 500 concurrent copies on 50th minute

**Comment by AntyaDev** [comment]
@gunmaden I think you abuse NBomber.
