### ISSUE TITLE
If there's multiple steps in scenario it's impossible to work with chart

### ISSUE THREAD

**Issue by gunmaden** [PragmaticFlow/NBomber#234]
If there's many (in my case 7 steps in scenario) there's no possibility to find some important data (maybe it relates to #231 )
![img](https://user-images.githubusercontent.com/7446973/89294530-b172e680-d670-11ea-9974-dc5c72503db1.png)

**Comment by AntyaDev** [comment]
@gunmaden can you describe what steps are doing, for example:
1. login
2. by product
3. logout

**Comment by gunmaden** [comment]
Sure
1. I register some emulators which perform background task (polling web service for tasks)
2. Create some entity through HttpClient
3. Some action which register in system event for emulators from step 1
4. Wait state of performed operation
5. Other action which register in system other event for emulators from step 1
6. Wait state of performed operation
7. Disposing emulators

**Comment by gunmaden** [comment]
Also I tried in different projects to add first dummy step
```csharp
Step.Create("Test", async context => await Task.FromResult(Response.Ok()))
```

1. In my project with my scenario with other steps I have 0 RPS
2. In dummy project with dummy scenario without other steps I have 397050 RPS

**Comment by AntyaDev** [comment]
@gunmaden 
I guess you receive 0 RPS because no one of your steps completed in less than 1 sec.
Also, I suggest testing specific action/endpoint separately

**Comment by gunmaden** [comment]
In case I add dummy step on first place I also have 0 RPS on it

**Comment by gunmaden** [comment]
I can't split steps further. So in case if we have steps that longs more than second we would have 0 RPS (so obviously 😀). Got it
