### ISSUE TITLE
Add response status code to reports

### ISSUE THREAD

**Issue by OlegZarevych** [PragmaticFlow/NBomber#242]
Hi,
I try to learn NBomber and have a few tests here https://github.com/OlegZarevych/ExploreSolutionBomberTests

It will be a great idea to add what response code we got to report. Now, presents only ok count and fail count

![зображення](https://user-images.githubusercontent.com/13772706/93015430-1ef42a00-f5c2-11ea-9e3a-359610f3ff68.png)

Have information about status code will be great for debugging and issue investigation

**Comment by AntyaDev** [comment]
Hi @OlegZarevych ,

I think we can think about it and provide an optional parameter for the Response record. 
And then you will be able to set status code like Response.Fail(statusCode, errroMSg)
After this, we can draw a segmented pie 

your PR is welcome!

**Comment by OlegZarevych** [comment]
@AntyaDev can you help me with the point from which I can start?

**Comment by AntyaDev** [comment]
@OlegZarevych 

try to extend the Response type to have an option param statusCode: int option
https://github.com/PragmaticFlow/NBomber/blob/dev/src/NBomber/Contracts.fs#L21
https://github.com/PragmaticFlow/NBomber/blob/dev/src/NBomber/Contracts.fs#L225

**Comment by AntyaDev** [comment]
Hi @OlegZarevych I did some progress for this feature https://github.com/PragmaticFlow/NBomber/commit/f6be0e920d29d31f9b68ccd7eda9303b0bffa81d

**Comment by OlegZarevych** [comment]
Hey @AntyaDev, 
I didn't have a chance to take a look at this. Unfortunately(
But, I will update my tests and check it

**Comment by OlegZarevych** [comment]
@AntyaDev thanks a lot !

**Comment by AntyaDev** [comment]
@OlegZarevych it's still not complete but in progress. Soon, we add an additional errors chart with the table with errors status and error message. Our next version will have this feature complete. Thanks for the suggestion, your idea is cool!

**Comment by AntyaDev** [comment]
NBomber v2 already supports this feature
