### ISSUE TITLE
XUNIT Report does not generate

### ISSUE THREAD

**Issue by NewmanUser123** [PragmaticFlow/NBomber#244]
Hi,

Have downloaded the repo, have opened it in VSCode and installed the dependancies
I have navigated to the XUNIT test.
Have clicked on RUN
![image](https://user-images.githubusercontent.com/70748517/93892057-04b5fc80-fce4-11ea-83f7-38b347099250.png)

Test has run. But no report is generated.
![image](https://user-images.githubusercontent.com/70748517/93892093-0bdd0a80-fce4-11ea-9ea6-a60468547d76.png)

Am i doing something wrong?

**Comment by NewmanUser123** [comment]
have tried running dotnet test   (from inside Powershell)  - Same issue no report.


```
using System;
using System.Threading.Tasks;

using FluentAssertions;
using Xunit;

using NBomber.Contracts;
using NBomber.CSharp;

namespace CSharp.XUnit
{
    // in this example we use:
    // - XUnit (https://xunit.net/)
    // - Fluent Assertions (https://fluentassertions.com/)
    // to get more info about test automation, please visit: (https://nbomber.com/docs/test-automation)

    public class XUnitTest
    {
        Scenario BuildScenario()
        {
            var step = Step.Create("simple step", async context =>
            {
                await Task.Delay(TimeSpan.FromSeconds(0.1));
                return Response.Ok(sizeBytes: 1024);
            });

            return ScenarioBuilder.CreateScenario("xunit_hello_world", step);
        }

        [Fact]
        public void Test()
        {
            var scenario = BuildScenario()
                .WithoutWarmUp()
                .WithLoadSimulations(new[]
                {
                    Simulation.KeepConstant(copies: 1, during: TimeSpan.FromSeconds(2))
                });

            var nodeStats = NBomberRunner.RegisterScenarios(scenario).Run();
            var stepStats = nodeStats.ScenarioStats[0].StepStats[0];

            stepStats.OkCount.Should().BeGreaterThan(2);
            // stepStats.RPS.Should().BeGreaterThan(8);
            // stepStats.Percent75.Should().BeGreaterOrEqualTo(100);
            // stepStats.MinDataKb.Should().Be(1.0);
            // stepStats.AllDataMB.Should().BeGreaterOrEqualTo(0.01);
        }
    }
}
```

**Comment by NewmanUser123** [comment]
Also tried :

`	dotnet test --filter "FullyQualifiedName=CSharp.Xunit.XUnitTest.Test"`

to make sure i was running the file. No report is generated

**Comment by safrazd** [comment]
@NewmanUser123  can you verify if you getting any report in bin\Debug\netcoreapp3.1\reports of the project folder?

**Comment by NewmanUser123** [comment]
Hi @safrazd  - Looks like it is in that folder. Is there any way to get it to go to \Reports in the Solution, rather than the debug folder?

**Comment by AntyaDev** [comment]
@NewmanUser123 you will be able to set the report output folder in the next version. 
I have just added it: https://github.com/PragmaticFlow/NBomber/commit/5279f5c6a0b40b091b9698e47ff092aeb4958567

by default, NBomber saves all reports into "./reports" folder.
Also, you can read the console output or log output, NBomber prints the report folder path.
