### ISSUE TITLE
Data transfer showing random numbers

### ISSUE THREAD

**Issue by theolivenbaum** [PragmaticFlow/NBomber#245]
Hi!

I'm testing a simple HttpStep returning a fixed sizeInBytes : `Response.Ok(sizeInBytes: N)`: I expected the final report to show the correct data transmitted value, but it is instead showing some really strange numbers:

```
HttpStep.Create("step", context => 
      Http.CreateRequest("POST", "server-url")
             .WithCheck(async response =>  Response.Ok(sizeBytes:10000000)))
```

```
+----------------------+---------------------------------------------------------------+
| - data transfer      | min = 0 Kb | mean = 0.07 Kb | max = 0.13 Kb | all = 0.04 MB   |
+----------------------+---------------------------------------------------------------+
```

Any ideas?

**Comment by AntyaDev** [comment]
Hi @theolivenbaum , I have to highlight it in documentation: when you are using NBomber.Http you can't set your own value (mannualy) for response size. 
just return OK or Fail. Under the hood NBomber will set correct value.

**Comment by AntyaDev** [comment]
here you can find how NBomber.Http is doing this trick 
https://github.com/PragmaticFlow/NBomber.Http/blob/dev/src/NBomber.Http/Api/FSharp.fs#L85

**Comment by AntyaDev** [comment]
Btw, I think I can fix it to allow passing custom value. It doesn't make much sense in terms usage, since when you use Http you shouldn't manually set response size, NBomber should take care of it.

**Comment by theolivenbaum** [comment]
TBH I was just trying to set the correct value because it was not showing the correct values from the response. Maybe the bug is that it's reading the response size before my call to ReadAsJsonAsync() ?

**Comment by theolivenbaum** [comment]
Ahh I see, the issue is that it requires a Content length field in the response header. As the endpoint I'm using is streaming the response, it doesn't write that header. Would be great to be able to overwrite the value in this case.

**Comment by AntyaDev** [comment]
@theolivenbaum maybe you can set completionOption = HttpCompletionOption. ResponseContentRead

By default NBomber.Http is set completionOption = HttpCompletionOption.ResponseHeadersRead for performance optimizations.

https://nbomber.com/docs/plugins-http#http-step

**Comment by theolivenbaum** [comment]
I tried that one too, but didn't seem to work either... Will check tomorrow
again if I did anything wrong. Maybe it's the combination with returning a
response object with any of the fields set

**Comment by AntyaDev** [comment]
Hi @theolivenbaum , any news?

**Comment by theolivenbaum** [comment]
Checking now. Btw another thing I noticed, HttpStep is missing an overload to pass HttpCompletionOption that only takes a name:

```csharp
public class HttpStep
    {
        public static IStep Create(string name, Func<IStepContext<Unit, Unit>, HttpRequest> createRequest);
        public static IStep Create<TFeedItem>(string name, IFeed<TFeedItem> feed, Func<IStepContext<Unit, TFeedItem>, HttpRequest> createRequest);
        public static IStep Create<TFeedItem>(string name, IFeed<TFeedItem> feed, Func<IStepContext<Unit, TFeedItem>, HttpRequest> createRequest, HttpCompletionOption completionOption);
        public static IStep Create(string name, Func<IStepContext<Unit, Unit>, Task<HttpRequest>> createRequest);
        public static IStep Create<TFeedItem>(string name, IFeed<TFeedItem> feed, Func<IStepContext<Unit, TFeedItem>, Task<HttpRequest>> createRequest);
        public static IStep Create<TFeedItem>(string name, IFeed<TFeedItem> feed, Func<IStepContext<Unit, TFeedItem>, Task<HttpRequest>> createRequest, HttpCompletionOption completionOption);
    }
```

missing:

```csharp
public static IStep Create(string name, Func<IStepContext<Unit, Unit>, HttpRequest> createRequest, HttpCompletionOption completionOption);
```

**Comment by theolivenbaum** [comment]
Ok tested with passing and still showing random data transfers with HttpCompletionOption.ResponseContentRead, and without using a custom WithCheck(...) step

**Comment by AntyaDev** [comment]
ok, strange I remember that this ResponseContentRead helped for some customer.
I will add small fix and let you know.

**Comment by theolivenbaum** [comment]
Cool, thanks!

**Comment by AntyaDev** [comment]
https://github.com/PragmaticFlow/NBomber.Http/commit/49433dc9aa576c0d066b79eae427cd5bb47e55e4

**Comment by theolivenbaum** [comment]
Cool, I'll test it tomorrow!

**Comment by AntyaDev** [comment]
@theolivenbaum 
https://github.com/PragmaticFlow/NBomber.Http/commit/5039a844b0f7d55840aa1a15a2655de7a4f0151a
