### ISSUE TITLE
html report - latency distribution per time unit

### ISSUE THREAD

**Issue by vilinski** [PragmaticFlow/NBomber#255]
it seems the html reporter bar chart presents the increasing counter of response latencies - absolute number of requests sofar.

Maybe it's somehow interesting too. More useful were indeed if it were per time unit, in other words - request rate per reporting time period

Example of a scenario report with default load simulation and an empty step, instanly returning `Response.Ok()`

<img width="1149" alt="grafik" src="https://user-images.githubusercontent.com/259479/98010626-321fbb00-1df7-11eb-9baa-532e28ce84a4.png">

Also, to be exact, it looks like there is one scenario iteration too much counted. There are 3050 requests instead of 3000 (by injection rate 50/s during 60 s)

**Comment by AntyaDev** [comment]
thanks, @Yaroshvitaliy  I think it's your turn:)

**Comment by Yaroshvitaliy** [comment]
@vilinski Yes, indeed, it would be more useful to see requests rate per unit time.

**Comment by AntyaDev** [comment]
@Yaroshvitaliy I suppose you are going to add it? :)

**Comment by Yaroshvitaliy** [comment]
> @Yaroshvitaliy I suppose you are going to add it? :)

Yes, sure, a little bit later if not critical
