### ISSUE TITLE
Can't serialise NodeStats due to PluginStats

### ISSUE THREAD

**Issue by seertenedos** [PragmaticFlow/NBomber#256]
It would be great if the NodeStats could be serialized to json and the like for storage or the report format also supported json as i wanted to store it in a DB as is to comparison between runs and return via API if requested but the DataSet[] used for the plugin stats causes exceptions due to its looping nature.

**Comment by AntyaDev** [comment]
Hi @seertenedos ,
Can you please paste the error that you got?
I see that DataSet has [Serializable] attribute.

**Comment by AntyaDev** [comment]
ping @seertenedos

**Comment by seertenedos** [comment]
@AntyaDev sorry for the slow reply i missed the email notifications. In my case i was using the default json serialiser for webapi responses in dotnet 5. Basically i was planning to store the object in mongo and have webapi to return them but my temp code just kept it in memory and returned it and that is when i noticed that at least the System.Text.Json (i think that is correct) serialiser can't handle datasets. I suspect putting it into something like mongo which is bson but similar to json will have issue with that one part of the result. setting it to null does fix the issue but the data would be nice to have,

**Comment by AntyaDev** [comment]
Hi @seertenedos can you pls try to use NewtonSoft Json serializer. I tried and it works without problems. DataSet has [Serializabale] attribute, it should work out of the box.

**Comment by AntyaDev** [comment]
@seertenedos any updates?

**Comment by seertenedos** [comment]
sorry been focused on other things. We have been mostly using Mongo as it is already our database for apps and it allows the storage of all the params that goes into a load test and well as the results and ideally the reports so that via rest api we call pull reports at a later date to compare and we can compare results from similar tests automatically over time to check for deviations etc as part of a deployment pipeline. InfluxDb likely can do something similar but we just don't have instances of it in our environment currently.

**Comment by seertenedos** [comment]
Clearing the ping results worked around our issue so we have not needed to come back to it at the minute. I needed to focus on a December release deadline for the minute. I will likely look at improving our load test tools next year so you can close this if you want
