### ISSUE TITLE
No way to get the report file info apart from the logs

### ISSUE THREAD

**Issue by seertenedos** [PragmaticFlow/NBomber#257]
I wanted my app to grab the reports generated to save for display later but found the return object from a run does not include the full path to any reports created. Instead you need to go to the logs to find it. Setting the folder and file also is not going to help as another folder gets added between the folder you specify and the file and the file also has its name modified as well.

My aim was to save all that stats etc to MongoDB and save the HTML report as well so we can compare between runs and from different locations with a plan to add this to CI/CD long term

**Comment by AntyaDev** [comment]
Hi @seertenedos ,
I got your idea, I think we had this thing at some beta version but then after some refactoring, we dropped support.
I will think about returning it back.

**Comment by AntyaDev** [comment]
Hi @seertenedos 
I have added ReportFiles[]
check this out https://github.com/PragmaticFlow/NBomber/commit/73992b36e5fed3676c543c061280a0b0d712268f

**Comment by seertenedos** [comment]
thanks
