### ISSUE TITLE
Is it possible to access raw request time data? 

### ISSUE THREAD

**Issue by noddyOB** [PragmaticFlow/NBomber#275]
I've started using NBomber recently, and the `IReportingSink` allows access to summarised data at a given time period.
Is it possible to access the raw request timings so analysis can be carried out on the raw data?

Thanks.

**Comment by AntyaDev** [comment]
Hi @noddyOB ,
We haven't planed this as a feature but I think it's possible to add. Can you explain why do you need this?

**Comment by noddyOB** [comment]
Hi @AntyaDev,

We've found that recently we've been needing to visualise some of the data we're getting in ways that are much more difficult when trying to base it on aggregated or summarised data, such as the metrics that is exposed within an `IReportingSink`.
I was hoping that we would be able to create a data set which could then be imported and analysed separately.

**Comment by AntyaDev** [comment]
ok, I see what you mean.
We can add this functionality only for enterprise customers since it's a very rare case.
