### ISSUE TITLE
UnitTest returns null in GetEntryAssembly

### ISSUE THREAD

**Issue by ArthNRick** [PragmaticFlow/NBomber#279]
Hi!

The GetEntryAssembly method always returns null when running an xUnit project on NetFramework 4.6.
Please add a fix for this, and use GetCallingAssembly instead when null.

```cs
(Assembly.GetEntryAssembly() ?? Assembly.GetCallingAssembly()).GetCustomAttribute<TargetFrameworkAttribute>().FrameworkName
```

[Dependency.fs#L84 (CLICK HERE)](https://github.com/PragmaticFlow/NBomber/blob/master/src/NBomber/Infra/Dependency.fs#L84)

`Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    Task`1.GetResultCore(Boolean waitCompletionNotification)
    Task`1.get_Result()
    NBomberRunner.run(NBomberContext context)
    NBomberRunner.run(NBomberContext context)
    NBomberRunner.Run(NBomberContext context)
    SuitabilityLoadTest.ClientOperatingPermitsRequest_LoadTest() line 39
    ----- Inner Stack Trace -----
    Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
    Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)
    CustomAttributeExtensions.GetCustomAttribute[T](Assembly element)
    NodeInfo.init()
    TestHost.ctor(IGlobalDependency dep, FSharpList`1 registeredScenarios, SessionArgs sessionArgs)
    NBomberRunner.binder@1-8(TestInfo testInfo, NBomberContext context, IGlobalDependency dep, SessionArgs _arg1, FSharpList`1 _arg2)
    runSession@39-2.Invoke(FSharpResult`2 r)
    TaskBuilder.run[a](FSharpFunc`2 firstStep)
    --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
    TaskAwaiter.ThrowForNonSuccess(Task task)
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    TaskBuilder.bindTaskConfigureFalse[a,b](Task`1 task, FSharpFunc`2 continuation)
    TaskBuilder.run[a](FSharpFunc`2 firstStep)`

**Comment by AntyaDev** [comment]
Hi @ArthNRick ,
Thanks, for FIX.

your PR will be welcomed!

**Comment by ArthNRick** [comment]
> Hi @ArthNRick ,
> Thanks, for FIX.
> 
> your PR will be welcomed!

https://github.com/PragmaticFlow/NBomber/pull/280
