### ISSUE TITLE
is there a C# code for Create Simple HTTP Load Test per https://nbomber.com/docs/#create-simple-http-load-test?

### ISSUE THREAD

**Issue by tienle488** [PragmaticFlow/NBomber#308]
Hi.  I'm making good progress on https://nbomber.com/docs/#create-simple-http-load-test and would like to continue with C# for Create Simple HTTP Load Test but noted that there is nothing when I click on the C# tab.  Likewise with Create Production-ready HTTP Load Test.  For now, I'm going to try the F# option but I'm not familiar with this language yet.  Thanks in advance for your help,
Tien.

![image](https://user-images.githubusercontent.com/23621965/104533065-7c2ad700-55c6-11eb-93db-81809d3fc3a8.png)

**Comment by AntyaDev** [comment]
Hi @tienle488 
We have all our examples in C# here: https://github.com/PragmaticFlow/NBomber/tree/dev/examples/CSharpProd

**Comment by tienle488** [comment]
Thank you very much for your help! Will check it out.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by tienle488** [comment]
Hello Antya,

I tried to do a build Release and run it like the Getting Started Release, but my Release build is not working.  What am I doing wrong?  Please let me know.  Thanks in advance for your help!
Tien

________________________________

**Comment by tienle488** [comment]
Hi Antya,

I took a closer look at the cloned repo from GitHub and found the examples folder with CSharp Release build with executables that work per the attachment.  What am I not doing resulting in the practically empty folder after Build Solution (Release) per the earlier screenshot attached?  Thanks in advance for your help.
Tien

________________________________

**Comment by AntyaDev** [comment]
Hi @tienle488 
What GIT branch did you use? I suppose it's master?

**Comment by tienle488** [comment]
Yes, I have not branched out to any new branch yet.  Thanks,
Tien

________________________________

**Comment by tienle488** [comment]
Figured it out, Antya.  I needed to enable another test run, i.e. HttpTests.SimpleHttpTest.Run(); and disable the
//HelloWorld.HelloWorldExample.Run();
from the Program.cs file

Build Solution or F5 updated the Release folder which allowed me to run my test from CLI as expected.  🙂

Thanks,
Tien

________________________________

**Comment by tienle488** [comment]
Hello Antya.  NBomber is working for my testing finally.   Now, how do i speed up the RPS to 1.1 instead of .28?

Any insight is appreciated!

Thanks in advance for your help,
Tien


Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by tienle488** [comment]
I should have closed this a while back.  Thanks.
