### ISSUE TITLE
What can I do to speed up my load test using NBomber? (VS LT 250 RPS easily; NBomber maxed with 25 RPS)

### ISSUE THREAD

**Issue by tienle488** [PragmaticFlow/NBomber#314]
Hi.  We've been using Visual Studio Load Test to exercise our .NET Framework 4.7.2 telemetry client where we can set up the load test to post metrics to our Rabbit MQ at a rate of about 250 metrics per second. Recently, we've had to migrate our telemetry client to .NET Core and need to run load testing and verify that it can still post metrics at the same rate. 

Now, Visual Studio Load Test (VSLT) is being deprecated and has no support for .NET Core framework so we've had to look to something like this solution, NBomber, to use in place of VSLT.

Currently, I've tried all I know and cannot get NBomber to post more than 25 metrics per second. At the same time, I'm seeing 100% CPU usage.

Any insight is appreciated. Thanks in advance for your help, 
Tien

**Comment by AntyaDev** [comment]
Hi @tienle488 

25 requests per second are not a big number for NBomber.

It would be great if you can send me your NBomber scenario example.

**Comment by tienle488** [comment]
Hi @AntyaDev 
Thank you for your prompt reply.  Sure.  Here it is:

public class TelemetryClientLoadTests
    {

        public static void Run()
        {
            var step1 = Step.Create("step_1", async context =>
            {
                PostTheMetric();

                await Task.Delay(TimeSpan.FromSeconds(.001));
                return Response.Ok(sizeBytes: 1024);
            });

            var scenario = ScenarioBuilder
                .CreateScenario("25 clients posting metrics for 56secs should result in 1.56k messages", step1) //, step2)
                .WithoutWarmUp()
                .WithLoadSimulations( new []{ Simulation.KeepConstant(copies: 1, during: TimeSpan.FromSeconds(56)) });

           NBomberRunner
                .RegisterScenarios(scenario)
                .WithTestSuite("whichTestSuite?NotSureAtThisTime")
                .WithTestName("TelemetryClientPostMetricLoadTest")
                .Run();

        }

        private static IDiContainer<IContainer> _container;
        private static readonly ILog Log = (ILog)LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);

        public TelemetryClientLoadTests()
        {
            var logRepository = LogManager.GetRepository(Assembly.GetCallingAssembly());
            XmlConfigurator.Configure(logRepository, new FileInfo("Log.config"));
        }

        private static ITelemetryClient _telemetryClient;
        private static IMetricCreator _metricCreator;

        public static void TelemetryClientLoadTestInitializer()
        {
            var environment = "qa"; //ConfigurationManager.AppSettings["environment"];
            //Console.WriteLine("environment value should be QA: ", environment);

            var builder = new ContainerBuilder();
            var telemetryBuilder = new TelemetryBuilder();
            var options = new Options
            {
                Environment = environment,
                ThrowIfFailedSending = false,
                IsDisabled = false,
                LoadingType = LoadingType.Eager
            };

            _telemetryClient = telemetryBuilder.Build(options);
            _metricCreator = new MetricCreator();

        }

        public static void PostTheMetric()
        {
            TelemetryClientLoadTestInitializer();
            var metric = _metricCreator.CreateValidMetricObject("");
            _telemetryClient.PostMetric(metric);
        }
    }

Thanks,
Tien
![nbomberStreamlinedTcPostMetricsTest XUnitTestRunYieldingAlreadyShowingHighCpuUsage](https://user-images.githubusercontent.com/23621965/106798863-6a5fb100-6613-11eb-9101-1d6a2da01d63.PNG)

**Comment by tienle488** [comment]
Got some help from a senior engineer, @AntyaDev and resolved the problem.  I'm killing it with NBomber load testing my telemetry client posting 300 metrics per second with just 5 clients and not yet 250 clients.  :-)

I moved the code around a bit so that I don't keep initializing and creating new telemetry client for every new metric post:
public class TelemetryClientLoadTests
{
    **TelemetryClientLoadTestInitializer();**

    public static void Run()
    {
        var step1 = Step.Create("step_1", async context =>
        {
            **var metric = _metricCreator.CreateValidMetricObject("");
            _telemetryClient.PostMetric(metric);**
            await Task.Delay(TimeSpan.FromSeconds(.001));
            return Response.Ok(sizeBytes: 1024);
        });

        var scenario = ScenarioBuilder...

**Comment by AntyaDev** [comment]
Ah I see

btw, not sure how your metrics client works but usually metrics sends on the background thread by batches with some time interval and not by on-demand requests. In other words when you invoke _telemetryClient.PostMetric(metric) - it doesn't mean that metric will be sent immediately. Again I am not sure that this is true for your _telemetryClient library.

**Comment by tienle488** [comment]
Hi @AntyaDev 
Not sure how I can truly respond to "it doesn't mean that metric will be sent immediately".  I believe it is.  The way our telemetry platform is designed, external services and applications using our telemetry client sends the telemetry platform messages via our Rabbit MQ queue where our metric processor is designed to consume and processes those messages up to 1MM message an hour.  Our telemetry platform is supposed to show metrics real-time via Grafana for our external services and applications.  Thanks.

**Comment by tienle488** [comment]
Should have closed this a while back.  thanks.
