### ISSUE TITLE
What can I do to achieve 1MM messages to Rabbit MQ after 1hr?

### ISSUE THREAD

**Issue by tienle488** [PragmaticFlow/NBomber#316]
Hi.  I’ve tried many things including meeting with a senior developer who has already helped me tremendously so far; however, I need additional insights about NBomber before I bug my busy friend again.  

![NBomberLoadTestingTelemetryClient NetCore VsRun_0 0095_Step1_copies250_1Scenario_636kMetricsAfter1h9mins](https://user-images.githubusercontent.com/23621965/107590711-b4213c00-6bbd-11eb-936f-f5aea9fea4f3.PNG)
Per the attachment above, my latest attempt is with step1 (scenario1)/post a metric/message to Rabbit MQ – do this 250 times for 4140 seconds or 69mins and expecting 1MM messages in the Rabbit queue.  Unfortunately, the test runs using more and more CPU (from about 20%) till it pegs 100% with which the test dwindles down to posting 1 metric per second resulting in only about 636K of messages instead of the expected 1MM messages.

What am I not doing or incorrectly done that’s causing this issue?

This test is with a .NET Core 3.1 version of a telemetry client that Visual Studio Load Test doesn’t support.  VS LT is being deprecated and supports up to .NET Framework 4.7.2 with which works excellent for that version of our telemetry client.  Reference 2nd screenshot:
![VSLT posted1MM_metrics 1h11mins](https://user-images.githubusercontent.com/23621965/107590761-d7e48200-6bbd-11eb-93dd-ca87376a76db.png)

Thanks in advance for your help!
Tien

**Comment by AntyaDev** [comment]
Hi @tienle488 
> the test runs using more and more CPU (from about 20%) till it pegs 100%
It's because NBomber v1 works inefficiently with memory for long-running (30min-1h) scenarios.
NBomber v2 should fix it. We going to release the first beta on this or next week.

**Comment by tienle488** [comment]
Got it.  Thanks, @AntyaDev !!  I appreciate the prompt reply!

**Comment by tienle488** [comment]
Hello @AntyaDev 
Any ETA on v2 being released this week?  Please LMK.  Thank you kindly,
Tien.

**Comment by AntyaDev** [comment]
HI @tienle488 ,
We faced with some issues, therefore we will try to publish beta on this week.

**Comment by tienle488** [comment]
All righty.  Thanks,  @AntyaDev !

**Comment by tienle488** [comment]
Hello @AntyaDev  I hope this message finds you well.  Just wanted to follow up and see how's it going with v2 or v2Beta.  Please let me know.  Thank you.
Tien.

**Comment by tienle488** [comment]
Hello @AntyaDev   I hope this message finds you well.  Just wanted to follow up and see how things are going?  Any update for me?  Thanks in advance for your help.  :-)

**Comment by AntyaDev** [comment]
Hi @tienle488 
NBomber 2.0.0 beta was published
https://www.nuget.org/packages/NBomber/2.0.0-beta

**Comment by tienle488** [comment]
Thank you, sir!!
Tien

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by tienle488** [comment]
Hello @AntyaDev 

I updated the NBomber NuGet but my test is now with error "Error	CS4010	Cannot convert async lambda expression to delegate type 'Func<IStepContext<Unit, Unit>, Response>'. An async lambda expression may return void, Task or Task<T>, none of which are convertible to 'Func<IStepContext<Unit, Unit>, Response>'.	CryptoClient.LoadTests.Core.NBomber..."

This is my code:
[Fact]
        public void DecryptTest()
        {
            var step1 = Step.Create("step1", async context =>
            {
                Logger.Info("Running DecryptTest");

                var sectionName = "s1";
                var settings = ((NameValueCollection)ConfigurationManager.GetSection(sectionName));
                var value = settings["melvin"];
                ConfigurationManager.RefreshSection(sectionName);

                Assert.Equal("some value", value);
                
                await Task.Delay(TimeSpan.FromSeconds(0.001));
                return Response.Ok();

            });

            var scenario1 = ScenarioBuilder
                .CreateScenario("scenario1: 1130 clients decrypting for 10secs", step1)
...

Can you take a look and provide any suggestion?  Thanks in advance for your help,
Tien.

**Comment by AntyaDev** [comment]
Hi @tienle488 ,
If you want to use the latest updates then you can check these examples (they always will be updated to the latest changes)
CSharpDev - means it aligned to the latest changes from the NBomber dev branch
https://github.com/PragmaticFlow/NBomber/tree/dev/examples/CSharpDev

Here you can find that for your use case you should use Step.CreateAsync
https://github.com/PragmaticFlow/NBomber/blob/dev/examples/CSharpDev/HelloWorld/HelloWorldExample.cs#L12

**Comment by AntyaDev** [comment]
Later on, I will update the documentation but for now, you can follow examples

**Comment by AntyaDev** [comment]
@tienle488 I will rollback this API change and you will be able to use Step.create as in v1

**Comment by AntyaDev** [comment]
@tienle488 pls use beta 3
https://www.nuget.org/packages/NBomber/2.0.0-beta3

**Comment by tienle488** [comment]
Thank you so much for your help, @AntyaDev!!

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tienle488** [comment]
Hello @AntyaDev 

You might be aware of it already but my 10 secs preliminary test is now taking almost 24mins to complete and requests are about half of the expected number of requests.  Reference the attachment.  Will there be another version released to resolve this problem?  Please let me know.  Thanks!
Tien.
![csep1595 NetCoreTcWrappingUp1MmTestWithNBomberV2 0 0Beta5 10secsTestTakingAbout24mins](https://user-images.githubusercontent.com/23621965/110751267-7c2b0a00-81f8-11eb-8e5e-afd315da9021.PNG)

**Comment by AntyaDev** [comment]
Hi @tienle488 I don't really know what happened to your tests.
It would be great if I could somehow simulate your test. 
Maybe you can write something very abstract that shows the same performance?

**Comment by tienle488** [comment]
Hello @AntyaDev 

After I revert back to v1, tests run fine except for more than half hour - all my CPU is consumed and I don't get to the 1MM metrics desired as reported.  While I'm thinking up a way to share so that you can reproduce the problem from your end, with Beta6, I tried running the 1hour load test anyway and running into another issue ".NET Debugging Services ran out of memory".  Reference screenshot:
![NBomberV2 0 0-beta6InB2bPlatformLoadTests_Program csTestYields NetDebuggingServicesOutOfMemory repeatable](https://user-images.githubusercontent.com/23621965/112229327-0491ad80-8bf0-11eb-8866-1790ea17b75d.png)

I ran it with the latest NBomber solution and SimpleHttpTest, I'm repeating the problem there as well.  Reference attachment:
![NBomberV2 0 0-beta6InItsOwnSolutions_Program csTestYields NetDebuggingServicesOutOfMemoryAlso wDiagnosticToolsAndTaskManager DebugRun](https://user-images.githubusercontent.com/23621965/112229388-1ffcb880-8bf0-11eb-961f-2414889d9793.PNG)

Have you seen this issue?  Thanks, Antya.
Tien

**Comment by AntyaDev** [comment]
Hi @tienle488 
First, you shouldn't run any of your production tests under debugger - debugger is always slowdown tests and consumes additional memory and CPU. With NBomber v2 you shouldn't face memory issues since it compacts all results.

**Comment by tienle488** [comment]
Hello @AntyaDev 
I ran it first with Release and saw the problem.  Reference top attachment of my earlier message.  Should have highlighted that like the Debug one per the second attachment.  Per Microsoft's documentation on the problem, I saw nothing for Memory Usage of Diagnostic Tools and thought running with Debug may help and nothing there as well.  Strange.  Thanks,
Tien.

**Comment by AntyaDev** [comment]
Hi @tienle488 
Recently we released a new version of NBomber 2.0.0 rc5 that fixes many performance bugs.
Can you please try it out on your test?
