### ISSUE TITLE
InfluxDB Sink and authorization?

### ISSUE THREAD

**Issue by Fredrik-C** [PragmaticFlow/NBomber#337]
InfluxDbSinkConfig.Create does only accept url and dbname. How do I supply/decorate with an authorization header?

**Comment by AntyaDev** [comment]
Hi @Fredrik-C ,

You can take a look at this example
https://www.app-metrics.io/reporting/reporters/influx-data/

var config = MetricsBuilder().Report.ToInfluxDb(options => {
    options.InfluxDb.UserName = "admin"
    options.InfluxDb. Password = "password"
}).Build();

using influxDb = new InfluxDBSink(config);

**Comment by AntyaDev** [comment]
@Fredrik-C 
In version 2.0.0-rc3 you can pass username and password as native arguments via config
