### ISSUE TITLE
Licensing issue with HTML report?

### ISSUE THREAD

**Issue by cdashrowe** [PragmaticFlow/NBomber#343]
Hello there.

We are currently looking at NBomber for doing some load testing of our commerical application, I can see NBomber is licensed with Apache 2, but I have some concerns about the HTML report.

You seem to use Highcharts to generate the chart information for test runs, this is a commerical product and I can't get my head around how the licensing for that would work here.

Could you clarify around the licensing/usage of Highcharts, and how that would affect any commerical project using NBomber to test please?

Thanks.

**Comment by AntyaDev** [comment]
Hi @cdashrowe 
Regarding HTML report - they support Non-commercial License and we use it as is.

**Comment by cdashrowe** [comment]
Thanks, we have the plans of sticking with it, the license was a concern and whether we'd need to fork and remove references to Highcharts.

I'm not completely clued up, but does your non-commerical license translate to being acceptable for a commerical entity generating html reports using your product?

**Comment by AntyaDev** [comment]
It's a good question.

I thought that if your outcome that you sell doesn't include this library then you are ok to use it.

For NBomber **Enterprise** it will be an issue since we sell our product and the outcome result includes this library.

**Comment by AntyaDev** [comment]
Hi @cdashrowe 
After a discussion about this issue, we decided to stick with https://www.chartjs.org/

**Comment by cdashrowe** [comment]
That's perfect, thank you for the fast response.

Is an ETA on when that change will take place?

**Comment by AntyaDev** [comment]
you are welcome
We will try to do it by the end of next week.
But for sure NBomber v2 release will not depend on Highcharts.

**Comment by cdashrowe** [comment]
Absolutely perfect, thank you very much!

**Comment by AntyaDev** [comment]
removed https://github.com/PragmaticFlow/NBomber/commit/18e7d0a0d2838f30fce7441e4d9bec0421068427
