### ISSUE TITLE
Option to specify exact number of runs, without setting TimeSpan.

### ISSUE THREAD

**Issue by stamen-petrov** [PragmaticFlow/NBomber#345]
I couldn't find an option to run a step an exact number of times, irrelevant of the TimeSpan set. That would be useful if for example a volume load test is performed on the system, where we expect to have exact number of records after the test is finished.

**Comment by AntyaDev** [comment]
NBomber doesn't support it out of the box.
As a workaround, you can define a global counter and when it reaches 100 requests you can stop test via context.StopTest()

```csharp
var step1 = Step.Create("step_1", async context =>
{
     if globalCounter => 100 then context.StopTest()
}
```
