### ISSUE TITLE
Make Scenario.GetStepsOrder configurable via JSON config

### ISSUE THREAD

**Issue by AntyaDev** [PragmaticFlow/NBomber#373]
[Scenario.GetStepsOrder](https://github.com/PragmaticFlow/NBomber/blob/dev/src/NBomber/Contracts/Contracts.fs#L128) returns an order of steps to be executed. By default it returns sequential order of steps: [0, 1, 2, 3]. But user can override it and even introduce random order.

It would be great if we could configure this order via JSON config. Yes, it will not have any randomality that you can get via code but still, it's quite convenient. 

For example, user can define 2 steps with such order: step_1 => step_2 
and using configuration JSON it can change order to: 
- step_2 => step_1, 
- or invoke only step_1 
- or introduce repeating step_1 => step_1 => step_1.

in JSON it could be something simple:

```json
{
  "GlobalSettings": {
    "ScenariosSettings": [
      {
          "ScenarioName": "test_youtube",
          "WarmUpDuration": "00:00:02",

          "LoadSimulationsSettings": [{ "KeepConstant": [2, "00:00:02"] }],
          "StepOrder": [0, 1]    
      }
    ],
  }
}
```

You can look at how for example [LoadSimulationsSettings](https://github.com/PragmaticFlow/NBomber/blob/dev/src/NBomber/Configuration/Configuration.fs#L25)
 maps to [Scenario.LoadSimulation](https://github.com/PragmaticFlow/NBomber/blob/dev/src/NBomber/Contracts/Contracts.fs#L127)
 
In addition, we can add support of named steps for configuration JSON:
so instead of having: "StepOrder": [0, 1] - this is our default form 
we could have more declarative way: "StepOrder": ["step_1", "step_2"]

**Comment by yurii-hunter** [comment]
PR is merged. Closing this issue
