### ISSUE TITLE
PingPluginHintsAnalyzer print received latency value

### ISSUE THREAD

**Issue by AntyaDev** [PragmaticFlow/NBomber#376]
The current PingPluginHintsAnalyzer prints error message like this:

"Physical latency to host: 'nbomber.com' is bigger than 2ms which is not appropriate for load testing. You should run your test in an environment with very small latency."

But it doesn't say anything about the real latency that it received.
The real latency contains in [PingReply.RoundtripTime](https://github.com/PragmaticFlow/NBomber/blob/077864935721995a06b2c8a77592c4c8e4fc8dd7/src/NBomber/Plugins/PingPlugin.fs#L96)

**Comment by dominiqueplante** [comment]
@AntyaDev change for this is here ;) https://github.com/PragmaticFlow/NBomber/pull/379
