### ISSUE TITLE
Data feed - random null values

### ISSUE THREAD

**Issue by dominikjeske** [PragmaticFlow/NBomber#387]
I'm using data feed option - 4 test clients data from CSV. Data is loaded ok but when test is executing (scenario Simulation.KeepConstant with 4 copies and 5 minutes long) I have random null value in context.FeedItem. Its is usually from 1 to 10 nulls per 10000 requests.

**Comment by AntyaDev** [comment]
Hi @dominikjeske ,
This week we also found this bug. It happens only with circular data feed because of using [not thread-safe enumeration](https://github.com/PragmaticFlow/NBomber/blob/dev/src/NBomber/Domain/Feed.fs#L48). 

We will publish a fix this weekend.

**Comment by AntyaDev** [comment]
Hi @dominikjeske 
check this out https://www.nuget.org/packages/NBomber/2.0.2
