### ISSUE TITLE
Make Loadsimulation more flexible

### ISSUE THREAD

**Issue by Fredrik-C** [PragmaticFlow/NBomber#395]
I would like to see more flexibility than the current options.
I would be nice if there wouble be an option to:
`Simulation.InjectPerSec(int rate, Timespan during)`
Perhaps?
`Simulation.Inject(int rate, Timespan during, Timespan injectionInterval)`

This would be usefull when you have several parallell scenarios running and would like to simulate "a invocation each 10 seconds"

**Comment by AntyaDev** [comment]
Hi @Fredrik-C 
You can use Step.CreatePause(seconds 10)

**Comment by Fredrik-C** [comment]
@AntyaDev Yes that is almost what I want. But that wont nececarily mean a invocatio each 10 seconds depending on how long time the previouse steps took to execute.

So idealy either:
`Simulation.Inject(1, someduration, TimeSpan.FromSeconds(10))`
or
`Step.CreatePause(() => TimeSpan.FromSeconds(10) - <hook_to_current_scenario_execution>.Duration)`

**Comment by AntyaDev** [comment]
Maybe you have some reference to look at how other frameworks support this option?
