### ISSUE TITLE
Reuse same client with a closed System

### ISSUE THREAD

**Issue by mjeanrichard** [PragmaticFlow/NBomber#401]
Hi,

I am trying to LoadTest a System though MQTT. I would like to use `Simulation.KeepConstant` but have exactly one mqtt client per running scenario (thread). The MQTT client needs some time to connect and subscribe which I would like to do only one per thread and then just reuse the same client again (exactly one client per thread, since it is not threadsafe).

How can I make sure that I get the same instance of my client on each execution of my step for the same thread?

Currently I am doing this manually, by using a dictionary with the Scenario thread number to find the right client, but this seems a little hacky:
```csharp
private static readonly ConcurrentDictionary<int, MqttClient> _clientPool = new();

private static async Task<MqttClient> GetMqttClient(int threadNumber, CancellationToken cancellationToken)
{
  MqttClient client = _clientPool.GetOrAdd(threadNumber, key => new MqttClient("localhost"));

  if (!client.IsConnected)
  {
    // connect and subscribe
  }

  return client;
}

// In the Step I am useing the following line to get the Client:
MqttClient mqttClient = await GetClient(context.ScenarioInfo.ThreadNumber, context.CancellationToken);

 

```

**Comment by AntyaDev** [comment]
Hi @mjeanrichard ,

You should use Client Factory for this.
https://nbomber.com/docs/general-concepts#clientfactory

**Comment by mjeanrichard** [comment]
Thanks, for that really quick answer.

So basically, if I use `KeepConstant` and make sure that there are enough instances in the Pool it will work out. (That would not work with `InjectPerSec` though, but for my Problem thats fine.)

My Test-Steps does the following things:
- Connect to MQTT (if not already done)
- Subscribe to the topic where I expect the Response
- Publish the Request
- Wait a specified time (currently 500ms) for a reponse on the subscribed topic.

My test case is a request/response pattern that uses one topic per request/response pair. That makes it really easy to listen for the correct respone. But the pattern also works if you do not have a topic per request/response, you just have to verify if it is really the right message that was received.

**Comment by AntyaDev** [comment]
For InjectPerSec, it will probably work - it will depend on the ability to reuse the same task from the NBomber scheduler pool.
But yes it sounds tricky and InjectPerSec is designed for Open Model which is not composed with your test case with persisted connections (Closed Model).

Btw, Do you use NBomber JSON config to bootstrap your tests?

**Comment by mjeanrichard** [comment]
> Btw, Do you use NBomber JSON config to bootstrap your tests?
No, not yet.
