### ISSUE TITLE
Decaying RPS reported

### ISSUE THREAD

**Issue by nullpainter** [PragmaticFlow/NBomber#405]
In NBomber 2.0.3, RPS graphs in both the HTML and in Influx are decaying to zero. Is this expected behaviour?

If we compare this graph:

![image](https://user-images.githubusercontent.com/1732347/124209315-7063aa80-db3d-11eb-9846-959075c19738.png)

with the associated statistics:

![image](https://user-images.githubusercontent.com/1732347/124209375-87a29800-db3d-11eb-9b1b-04705599a5b9.png)

It appears that my step is running successfully (10RPS and 432,000 requests), but the RPS figure over time isn't particularly useful - particularly when filtering by a time period in Grafana.

**Comment by AntyaDev** [comment]
Hi @nullpainter 

In 2.0.3 we changed the logic to produce RPS stats per interval. In the previous versions (until 2.0.3) we published RPS for the whole test duration instead of the period.

This change was done by purpose since now you can identify the exact point in time where your RPS dropped or spiked.

**Comment by nullpainter** [comment]
Sorry, I'm not sure I fully understand. 

The screenshot below is from a 2.0.3 report, for a 12 hour NBomber run. There were 298,880 requests made for this step, and I'm using `InjectPerSec` of 7. As you can see from the tooltip, the quoted RPS is almost immediately 0 - which makes inferring anything almost from this graph impossible.

![image](https://user-images.githubusercontent.com/1732347/124827275-f5c9dd80-dfc9-11eb-8e01-c492f980e803.png)

**Comment by AntyaDev** [comment]
Hi @nullpainter 

Can you please set a bit higher load simulation, for example, InjectPerSec: 100
And also shorten duration period like 3 min and reporting interval: 10 sec.

**Comment by nullpainter** [comment]
Sure. Here's the results of a new, trivial step (just `Console.WriteLine()`) with the requested parameters:

![image](https://user-images.githubusercontent.com/1732347/124987516-10b35500-e091-11eb-90b3-599709699f45.png)

And the same step with a 15 minute duration and 5 second reporting interval:

![image](https://user-images.githubusercontent.com/1732347/124989666-7accf980-e093-11eb-9aeb-7443231f9252.png)
![image](https://user-images.githubusercontent.com/1732347/124989690-81f40780-e093-11eb-9192-ae8e11a85947.png)
