### ISSUE TITLE
No expected request count at the end of the test

### ISSUE THREAD

**Issue by mklpanasiuk** [PragmaticFlow/NBomber#407]
Hi! I'm considering taking NBomber as my load generator in future projects and playing with it right now. I've found not expected behavior with the request counts at the end of the test what confuses me so far. I see the same behavior for step with kafka or without (just with Task.Delay). I wonder how to achieve the real number of requests in my load test, what I'm doing wrong? Or at least what is the root cause of such behavior? (All details on screenshots. Question duplicated from gitter)  
![Snag_348cedb5](https://user-images.githubusercontent.com/53987913/127344640-b4b39924-4de7-407b-95ba-929065a28d02.png)
![Snag_348d094b](https://user-images.githubusercontent.com/53987913/127344662-31178946-8128-4a38-8f85-16449c5b1e2e.png)

**Comment by AntyaDev** [comment]
Hi @SkynetKoks 
You got different numbers because when NBomber stops counting (by specified duration, 10 sec), some of the steps at this moment were activated and continue execution one more time.

**Comment by SkynetKoks** [comment]
@AntyaDev Thank you for your response! It's not something you expect by default. Is there any chance to change this behaviour to count all the requests? Something like WarmTearDown\TolerantTearDown (under the hood: Task.WhenAll() )

**Comment by AntyaDev** [comment]
@SkynetKoks I am not sure how to model such behavior.
let say you set scenario duration = 5 min
and now your step is activated at 4:59 (basically you have 1 sec to finish)
what should I do with this step? should I include this step in overall statistics? (but it's just started and not yet finished, and it may take 5 sec to complete).
now, what if you have 1-2K steps at 4:59? if you include them in stats they can affect your RPS (request per sec).

**Comment by AntyaDev** [comment]
I guess this behavior requires introducing a special load simulation where you set a total number of requests to be sent instead of duration.

**Comment by SkynetKoks** [comment]
@AntyaDev Again, thanks for your answers! I see your point. For me it seems that InjectPerSecTotal(rate, total) will not completely solve my issues, as I need to manually calculate the total number based on time I want to run the test. 
Some my thoughts:
- I would count additional requests at 4:59 in order to see the accurate total requests count
- the root cause of the issue I created is that you lose functional mechanizm to check your system under stress to see how much messages/request it will lose. I use JMeter and it counts total request as it should be (waiting for already started requests), but I'm a bit tired from JMeter, that's why I look at NBomber

**Comment by AntyaDev** [comment]
@SkynetKoks I see you use LoadSimulation KeepConstant
Why not InjectPerSec?

**Comment by SkynetKoks** [comment]
@AntyaDev It was just for testing, I'm not using it on real scenarios so far. By the way, it gives almost the same small difference: 
- 100 requests in the report
- 104 requests in reality

**Comment by AntyaDev** [comment]
@SkynetKoks I think I have a plan)

**Comment by RefaelP23** [comment]
@AntyaDev this issue relates also to #415 as well, with the main question being: how to treat inflight steps?

**Comment by AntyaDev** [comment]
Hi @RefaelP23 , @mklpanasiuk 
I have added improvements that speedups the cancellation for in-flight steps.

**Comment by AntyaDev** [comment]
@RefaelP23 @mklpanasiuk 
I found another thing that produced such behavior and fixed it.
in the next beta version, you will be able to try
https://github.com/PragmaticFlow/NBomber/commit/c02cdad0e84b9e3b638c2702099bcfd907e2e7f0
