### ISSUE TITLE
Different Request Count for Two Steps

### ISSUE THREAD

**Issue by Tandis5** [PragmaticFlow/NBomber#415]
Just wanted to start off by saying I just started playing around with NBomber and so far I love it!  But, here is my problem...

Maybe I'm doing something wrong here, but I have the following scenario:

I have two steps I created.  Both are making HTTP calls to a web API.  Both are checking for an OK response from the API and returning Response.Fail if it doesn't (and obviously returns Response.OK if the API did return OK).  I then setup a Scenario with the two steps, using Simulation.KeepConstant to have 5 copies running for 10 seconds.  Here is my output:

```
scenario: 'Void Sale Scenario'                                                         
duration: '00:00:10', ok count: 585, fail count: 0, all data: 0 MB                     
load simulation: 'keep_constant', copies: 5, during: '00:00:10'                        
┌────────────────────┬─────────────────────────────────────────────────────────┐       
│               step │ ok stats                                                │       
├────────────────────┼─────────────────────────────────────────────────────────┤       
│               name │ Scan Item                                               │       
│      request count │ all = 294, ok = 294, RPS = 29.4                         │       
│            latency │ min = 47.96, mean = 67.76, max = 546.1, StdDev = 56.28  │       
│ latency percentile │ 50% = 57.57, 75% = 63.39, 95% = 78.66, 99% = 395.52     │       
│                    │                                                         │       
│               name │ Void Transaction                                        │       
│      request count │ all = 291, ok = 291, RPS = 29.1                         │       
│            latency │ min = 81.42, mean = 101.81, max = 328.72, StdDev = 23.3 │       
│ latency percentile │ 50% = 98.11, 75% = 105.73, 95% = 121.66, 99% = 153.47   │       
└────────────────────┴─────────────────────────────────────────────────────────┘       
                                                                                       
status codes for scenario: Void Sale Scenario                                          
┌─────────────┬───────┬─────────┐                                                      
│ status code │ count │ message │                                                      
├─────────────┼───────┼─────────┤                                                      
│         200 │  585  │         │                                                      
└─────────────┴───────┴─────────┘                                                      
```

As you can see, the request count for the first step is 294, with all 294 completing successfully.  But the second step only ran 291 times, with all 291 completing successfully.  When the 10 seconds ends, do all tests stop immediately even if they are in the middle of a scenario run?  Or am I doing something else wrong?  Any help in understanding how this can happen would be greatly appreciated!

**Comment by AntyaDev** [comment]
Hi @Tandis5 

Thanks for your feedback :)

> When the 10 seconds ends, do all tests stop immediately even if they are in the middle of a scenario run?

Yes. NBomber stops all steps even if they are in the middle of the scenario run. And in your case, some of your steps finished in 10 sec but some of them may be started but finished later (say at 12 sec) and NBomber doesn't include their results (even if they finished successfully)

**Comment by Tandis5** [comment]
Hi @AntyaDev 

Thank you for the quick reply!  So the steps still complete, even if the test run has completed?  For instance, let's say I have 5 steps in my load test, and the test ends with one scenario being on step 2.  Even if the results of steps 2 through 5 not being in the results, will they still run?  Or is there a chance that 3 through 5 won't run at all?  My issue is that, each step of my test will be updating a database, and by not having the test run through all of the steps, it could leave awkward data in the database.

**Comment by AntyaDev** [comment]
NBomber is using [CancellationToken](https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken?view=net-5.0) to stop steps execution.
You can get it via context.CancellationToken.

Regarding inflight steps and immediate test stop: most likely that after test stop some of steps (inflight) will still be active some time because of waiting on a response from HTTP server or Database. And their statistics will not be taken since they exceeded scenario duration.

Maybe you can use context.InvocationCount property to somehow stop sending requests when you reach some criteria.
Also, you can use context.StopTest() to stop the test at any given time.

**Comment by AntyaDev** [comment]
Hi @Tandis5 
I have added improvements that speedups the cancellation for in-flight steps.
The main issue is that default CancellationToken propagation is slow
https://github.com/PragmaticFlow/NBomber/commit/343f87d8ad6da6340dec2802cbe54b5d69d7a3ae

**Comment by AntyaDev** [comment]
Hi @Tandis5 
I found another thing that produced such behavior and fixed it.
in the next beta version you will be able to try
https://github.com/PragmaticFlow/NBomber/commit/c02cdad0e84b9e3b638c2702099bcfd907e2e7f0
