### ISSUE TITLE
[Documentation] Navigation menu's to the plugin documentation

### ISSUE THREAD

**Issue by Abhith** [PragmaticFlow/NBomber#421]
It looks like the nav menu's for the plugin documentation missing in the main menus (sidebar, header).

![image](https://user-images.githubusercontent.com/7039457/133897250-d4cfe4d2-1db3-40fb-802f-3c37a3e4ea04.png)

Better if we have a menu to reach to this page,

![image](https://user-images.githubusercontent.com/7039457/133897280-c677b854-0c69-4242-986d-1479e9965fa8.png)

**Comment by AntyaDev** [comment]
Hi @Abhith 
Yes you are right, we will fix it.
Thanks
