### ISSUE TITLE
Wrong data saved to InfluxDB when there is no metrics at all

### ISSUE THREAD

**Issue by mklpanasiuk** [PragmaticFlow/NBomber#422]
Default metrics handler - InfluxDBSink - from NBomber cannot save null data points to InfluxDB, in other words, it saves always the last value. See the example on the attached screenshot
![2021-09-30_10-27-02](https://user-images.githubusercontent.com/53987913/135410140-05e537f9-4108-497b-a630-8fd9d0fffcea.png)
**Problem**: it doesn't allow you to make queries to InfluxDB and get the total amount of requests that has been made during the whole test (as we will sum all count values)

**Comment by AntyaDev** [comment]
Hi @SkynetKoks 

We have a plan to change this behavior and finally release our Dashboard including rendering full statics tables.

**Comment by AntyaDev** [comment]
Fixed in InfluxSink v3
