### ISSUE TITLE
How to test ASP.NET Core gRPC server?

### ISSUE THREAD

**Issue by Oleg26Dev** [PragmaticFlow/NBomber#430]
Is it possible to use NBomber for load testing ASP.NET Core gRPC server ? if yes then how to ?
Thanx

**Comment by AntyaDev** [comment]
yes, of course, even PUSH scenario can be covered by NBomber.
You should create a gRPC client to your API and use it inside NBomber Step.

for example:
```csharp
var grpcClientFactory = ...

var grpcStep = Step.Create("grpc_step", clientFactory: grpcClientFactory, execute: async context => 
{
    var result = await context.Client.YourGRPCAPIEndpoint("some arguments");
    return Response.Ok(result);
})
```

**Comment by Oleg26Dev** [comment]
Дякую, протестую!
