### ISSUE TITLE
Constants.MaxSimulationDuration.ToString("hh\:mm\:ss"), the output is always 00:00:00

### ISSUE THREAD

**Issue by murrays1208049** [PragmaticFlow/NBomber#432]
Constants.MaxSimulationDuration.ToString("hh\:mm\:ss"), the output is always **00:00:00**

It is really misunderstood !!

**Comment by yurii-hunter** [comment]
Hi @murrays1208049.

This question is not about NBomber but more about [custom TimeSpan format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-timespan-format-strings?redirectedfrom=MSDN).

The short answer is that Constants.MaxSimulationDuration represents the time span of 10 days 0 hours 0 minutes and 0 seconds. That is why you see 00:00:00 when specifying hh:mm:ss.

You can specify ToString(@"dd\.hh\:mm\:ss") and the result will be 10.00:00:00.
