### ISSUE TITLE
Wrong calculation of users/threads for NBomber cluster

### ISSUE THREAD

**Issue by mklpanasiuk** [PragmaticFlow/NBomber#439]
**Steps to reproduce:**

1. Run the same scenario on Coordinator and Agent - 5 users for scenario

**Actual result:**

5 users 

**Expected result:** 

10 users = 5 users on Coordinator + 5 users on Agent

**Comment by mklpanasiuk** [comment]
@AntyaDev  Hi, my example
![Snag_435e4653](https://user-images.githubusercontent.com/53987913/148211696-e30b55f0-ddf0-467c-8f8d-b290167c0f11.png)

**Comment by AntyaDev** [comment]
ok, thanks

**Comment by mklpanasiuk** [comment]
@AntyaDev Hi, any updates about this issue?

**Comment by AntyaDev** [comment]
Hi, @mklpanasiuk I will try to bring the fix next week.

**Comment by AntyaDev** [comment]
fixed in NBomber.Cluster v3.0.0-beta
will be available from 10th of April
