### ISSUE TITLE
Add assertions by steps

### ISSUE THREAD

**Issue by Bonaqqa** [PragmaticFlow/NBomber#441]
Hi, it would be great to have a possibility to verify each Step separately, like in Gatling
`.assertions(
      details("Scenario name").responseTime.max.is(10)`

- responseTime.max
- responseTime.min
- responseTime.avg

**Comment by AntyaDev** [comment]
@Bonaqqa but NBomber gives you a collection of steps stats for this.
https://github.com/PragmaticFlow/NBomber/blob/dev/tests/NBomber.IntegrationTests/StepTests.fs#L56

**Comment by AntyaDev** [comment]
maybe you mean Scenario?

**Comment by Bonaqqa** [comment]
found it, thx for your response
