### ISSUE TITLE
Expected, actual and reported scenario copies doesn't always match

### ISSUE THREAD

**Issue by J0nKn1ght** [PragmaticFlow/NBomber#457]
Firstly, thanks for developing an excellent framework for .Net developers.

I'm using the nuget package v2.1.3., and have created a simple test that calls one of a list of URLs against my localhost website.

I have the InjectPerSec parameters set to a rate of 8 and a timespan of 10 seconds.  I've added a log entry in the execute function that just outputs the context.InvocationCount.

On the majority of runs, execute is called 80 times (which is what I would expect), but on some runs execute is called 88 times.  Despite the fact that it is called 88 times, the report still shows a request count of 80.  The log shows 88 entries, with invocation counts of 1 to 11.

Can you explain why this is happening?  I could perhaps understand if an extra invocation was made due to the run starting on an exact second boundary, or something, but why would it still report 80 requests, rather than the 88 which were actually made?

Here is the console app, and I've attached the log output & report:

```csharp
using NBomber.Contracts;
using NBomber.CSharp;
using NBomber.Plugins.Http.CSharp;
using System.Net.Mime;

namespace LocalMVCSite.LoadTests
{
    class Program
    {
        static void Main(string[] args)
        {
            string baseUrl = "https://localhost:44315";

            List<string> pageUrls = new List<string> {
                $"{baseUrl}/",
                $"{baseUrl}/about",
                $"{baseUrl}/shop",
                $"{baseUrl}/shop/test"
            };

            var feed = Feed.CreateCircular("pageUrls", pageUrls);
            var httpFactory = HttpClientFactory.Create();

            var step = Step.Create("pages",
                timeout: TimeSpan.FromSeconds(3),
                feed: feed,
                clientFactory: httpFactory,
                execute: async context =>
                {
                    context.Logger.Information($"Invocation: {context.InvocationCount}");

                    var request = Http.CreateRequest(HttpMethod.Get.ToString(), context.FeedItem)
                        .WithHeader("Accept", MediaTypeNames.Text.Html)
                        .WithCheck(async (response) =>
                            await Task.FromResult(response.IsSuccessStatusCode
                                ? Response.Ok(statusCode: (int)response.StatusCode)
                                : Response.Fail(statusCode: (int)response.StatusCode))
                        );

                    var response = await Http.Send(request, context);
                    return response;
                });

            var scenario = ScenarioBuilder
                .CreateScenario("pageUrls", step)
                .WithoutWarmUp()
                .WithLoadSimulations(Simulation.InjectPerSec(rate: 8, during: TimeSpan.FromSeconds(10)));

            NBomberRunner
                .RegisterScenarios(scenario)
                .LoadConfig("config.json")
                .Run();

        }
    }

}
```

Thanks for your help.

[nbomber_report_2022-02-02--15-49-05.txt](https://github.com/PragmaticFlow/NBomber/files/7988166/nbomber_report_2022-02-02--15-49-05.txt)
[nbomber-log-20220202.txt](https://github.com/PragmaticFlow/NBomber/files/7988167/nbomber-log-20220202.txt)

**Comment by AntyaDev** [comment]
Hi @J0nKn1ght 

You got different numbers because when NBomber stops counting (by specified duration, 10 sec), some of the steps at this moment were activated and continue execution one more time (but they will not be included in the final report because they started after NBomber finished test execution).

Does it make sense?

**Comment by J0nKn1ght** [comment]
Yes - thank you.  We were aiming to create integration tests that ran the load test, and then checked that the correct number of items had been created in a processing queue (i.e. one per request), but I guess that we can just check that the number of queue items is >= the expected request count, rather than just equal to it.

I've therefore closed this issue.

**Comment by AntyaDev** [comment]
Hi @J0nKn1ght 
I have fixed this, in the next beta version, you will be able to try it.

**Comment by J0nKn1ght** [comment]
That's awesome - thank you @AntyaDev
