### ISSUE TITLE
Crashes on 0.43 of Spectre.Console

### ISSUE THREAD

**Issue by isaacabraham** [PragmaticFlow/NBomber#460]
NBomber has a dependency on Spectre.Console of >= 0.38.0. However, if you use a newer version - same, 0.43, NBomber simply dies after showing the NBomber console banner. There's no exception, the runner just prematurely ends.

I would suggest pinning Spectre to specifically 0.38.0.

**Comment by rem-coding** [comment]
Hi @AntyaDev, @isaacabraham, I know this is closed, but are there plans to support later versions of Spectre.Console? I'm using more recent features in Spectre.Console in the same console app and ideally need more recent versions.

**Comment by AntyaDev** [comment]
Hi @rem-coding ,
I would say that it's not a critical feature for our next release. So, therefore, we most likely will postpone it.
But if you want to help the project your PR is welcome!

**Comment by rem-coding** [comment]
Understood, thanks @AntyaDev. If I make further changes to the particular code I'm working on, then will see if I can allocate time to a PR. Appreciate the work you do on a great project.
