### ISSUE TITLE
async/await problem workFlow

### ISSUE THREAD

**Issue by BratSvK** [PragmaticFlow/NBomber#461]
Hello, 
during implementing steps in the scenario i found a little tricky thing with async / await.
 In a code below i found a problem with asynchronous code.

`public void DemoTestingTest()
        {
            var step1 = Step.Create("step 1", async context =>
            {
               
                    await Task.Delay(TimeSpan.FromSeconds(1));

                    context.Logger.Information("step 1 is invoked!!!");
                    return Response.Ok();
            });

            //var thinkTime = Step.CreatePause(TimeSpan.FromSeconds(2));

            var step2 = Step.Create("step 2", async context =>
            {
                await Task.Delay(TimeSpan.FromSeconds(1));
                context.Logger.Information("step 2 is invoked!!!");

                return Response.Ok();
            });

            var scenario = BuildScenario(new [] { step1, step2 });

            NBomberRunner
                .RegisterScenarios(scenario)
                .LoadConfig("config.json")
                .Run();
        }`
response in the picture below:
![image](https://user-images.githubusercontent.com/45105319/161515048-6263514b-4469-4738-bebd-d1ff8abff804.png)

**

> OR PROBLEM IS WITH DEFAULT DURATION 1s

**
- thanks for response
- for now i will use .GetAwaiter().GetResult(); syncrounous way

**Comment by AntyaDev** [comment]
Hi @BratSvK 

Try to set timeout = 5 sec
Step.Create(timeout: TimeSpan.FromSeconds(10))

**Comment by BratSvK** [comment]
yes it helps. Thank you
