### ISSUE TITLE
Ability to configure GlobalSettings to pass to every Scenario, usable in methods such as WithInit

### ISSUE THREAD

**Issue by jimcomiskey** [PragmaticFlow/NBomber#463]
We have the ability to configure custom settings for a particular scenario, as shown in the example below:

`{
    "TestSuite": "public_api_test_suite",
    "TestName": "purchase_api_test",

    "TargetScenarios": ["purchase_api"],

    "GlobalSettings": {

        "ScenariosSettings": [
            {
                "ScenarioName": "purchase_api",
                "WarmUpDuration": "00:00:05",

                "LoadSimulationsSettings": [
                    { "InjectPerSec": [100, "00:00:15"] },
                    { "InjectPerSec": [200, "00:00:15"] }
                ],

                "CustomSettings": {
                    "BaseUri": "https://jsonplaceholder.typicode.com"
                }
            }
        ]       
    }
}`

I would like the ability to configure settings that could be applied to all scenarios the agent might run.  For example, BaseUri is the same for all scenarios, I don't want to configure that setting for every scenario.  But I do want to be able to change that setting when switching load testing from one environment to another, so I'd like to be able to pass this in so that the Init() procedure can authenticate to the API and allow my Scenario Steps to test the API I have targeted.

`{"GlobalSettings": {
       <-- add global settings here?
        "ScenariosSettings": [
            {
                "ScenarioName": "purchase_api",
                "WarmUpDuration": "00:00:05",

                "LoadSimulationsSettings": [
                    { "InjectPerSec": [100, "00:00:15"] },
                    { "InjectPerSec": [200, "00:00:15"] }
                ],

                "CustomSettings": {
                    "BaseUri": "https://jsonplaceholder.typicode.com"
                }
            }
        ]       
}`

**Comment by AntyaDev** [comment]
Hi @jimcomiskey 

There is GlobalCustomSettings.

```json
"GlobalCustomSettings": {            
    "ConnectionString": "my_db_connection_string"
}
```

https://nbomber.com/docs/nbomber/json-config#json-config
