### ISSUE TITLE
NBomber scenario stats showing incorrect ramp_constant, instead of the configured inject_per_sec

### ISSUE THREAD

**Issue by allanhaywood** [PragmaticFlow/NBomber#472]
When running NBomber cluster 3.0.0-beta5

The scenario stats shows ramp_constant, even though inject_per_sec is configured.

NOTE: It shows correctly when executing.

──────────────────────────────────────────────────── scenario stats ────────────────────────────────────────────────────

scenario: scenario_1
  - ok count: 5230
  - fail count: 0
  - all data: 0.0050 MB
  - duration: 00:01:00

load simulations:
  - ramp_constant, copies: 75, during: 00:00:30
  - ramp_constant, copies: 100, during: 00:00:30
  
  
  When running it is correct:
  
                     scenario_1 ---------------------------------------- 100% 00:00:00
load: inject_per_sec, rate: 0

00:43:08 [INF] Starting bombing...

                     scenario_1 ---------------------------------------- 100% 00:01:00
load: inject_per_sec, rate: 100

Config:

        "LoadSimulationsSettings": [
          { "InjectPerSec": [ 15, "00:00:30" ] },
          { "InjectPerSec": [ 20, "00:00:30" ] }

        ]
        
No settings in code.

**Comment by AntyaDev** [comment]
Hi @allanhaywood 
Thanks for a good catch.
Fixed in 3.0.0-beta6
