### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by kazimir-malevich** [PragmaticFlow/NBomber#474]
On this page: https://nbomber.com/docs/overview/

Under the heading https://nbomber.com/docs/overview/#create-production-ready-http-load-test

There is a broken link under **NBomber.HTTP **; https://nbomber.com/docs/overview/plugins-http

**Comment by nullpainter** [comment]
On the same page, the following links in the first section are also broken:

- [Cluster support](https://nbomber.com/docs/overview/nbomber-cluster)
- [Plugins support](https://nbomber.com/docs/overview/plugins-overview)
- [Realtime reporting](https://nbomber.com/docs/overview/reporting-overview)

- [DataFeed support](https://nbomber.com/docs/overview/general-concepts#datafeed)

**Comment by wilbit** [comment]
I think this issues is not relevant to the current documentation anymore.
Seems like https://nbomber.com site is reorganized.
