### ISSUE TITLE
Cannot use BaseAddress of the httpClient with NBomber.Plugins.Http

### ISSUE THREAD

**Issue by CrazyLlama98** [PragmaticFlow/NBomber#477]
I have a static helper to set Timeout and BaseAddress of http clients and creating the HttpClientFactory.
![image](https://user-images.githubusercontent.com/24496504/181293118-b75982d9-1839-40fb-ad0c-efb04fe443ca.png)

If I try to use CreateRequest method from plugin like this, using Relative Uri it fails when running load tests:
![image](https://user-images.githubusercontent.com/24496504/181293745-7c3f0a27-f038-4fcc-9b19-5c12400a7d9a.png)

And the resulted error in the console is this:
![image](https://user-images.githubusercontent.com/24496504/181294136-56d1ddf8-63d8-49f2-b518-52c5658380d2.png)

Am I using it wrong or it can be improved to support also relative paths there, like the one in HttpClient (used for all exposed methods with strings as url)?
```csharp
private static Uri? CreateUri(string? uri) =>
            string.IsNullOrEmpty(uri) ? null : new Uri(uri, UriKind.RelativeOrAbsolute);
```

**Comment by AntyaDev** [comment]
Hi @CrazyLlama98 
I think this case was not covered initially.
Can you try to prepare PR?

**Comment by CrazyLlama98** [comment]
Sure, I think it needs to be in the NBomber.Http. I will prepare it
